### ISSUE TITLE
Docker-compose connection refused error

### ISSUE THREAD

**Issue by skanjila** [Azure/Azurite#1749] opened 2022-11-08 20:24 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob Service

### Which version of the Azurite was used?
The latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Using docker-compose to reference latest image

### What's the Node.js version?
N/A

### What problem was encountered?
Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:10000
modelhub-web-1  |       Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused

### Steps to reproduce the issue?
I have a spring boot java application that uses docker-compose to spin up a spring API and a docker compose file that looks like whats shown below:
version: '3.9'
services:
    web:
      build:
        context: .
        args:
          - ARTIFACTORY_API_TOKEN
          - ARTIFACTORY_USER
      depends_on:
        - db
        - azurite
      ports:
        - "8080:8080"
        - "4000:4000"
      environment:
        - ENVIRONMENT_NAME=local
        - REGION_NAME=local
        - AZURE_STORAGE_CONNECTION_STRING=mylocalconnectionstring
        - AZURE_STORAGE_CONTAINER=localcontainercreatedinstorageexplorer
       #- JVM_OPTIONS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=4000

    db:
      image: 'postgres:15-alpine3.16'
      container_name: db
      environment:
        - POSTGRES_USER=compose-postgres
        - POSTGRES_PASSWORD=compose-postgres
    azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      container_name: "azurite"
      hostname: azurite
      restart: always
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"

1) I create a blob container in storage explorer under the key azurite
2) I start up my spring application on port 8080 using docker-compose up --build
3) I use postman to send an http post request to upload file
4) I get the following exception:
Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:10000
modelhub-web-1  |       Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
Yes I'm using azurite from the command line to get past this issue as opposed to docker-compose but would really like to get docker-compose working

**Comment by blueww** [comment] 2022-11-09 05:08
@skanjila 
Thanks for raising the issue!
However, I am really confused with it. 
Do you use same Azurite instance in step #1 (create container with Storage Explorer), and step #3 (upload file with postman)?
Do you run Storage Explorer and postman on same machine?
For Storage Explorer, do you also use 127.0.0.1 and port 10000?

As you can connect Azurite with Storage Explorer, but connection refused with postman, it looks this is not Azurite issue, but some configuration/network issue in your local environment.

**Comment by skanjila** [comment] 2022-11-09 16:00
@blueww Its not confusing at all, yes I run Storage Explorer and Postman on the same machine and yes I use port 10000 with Storage Explorer.  The connection refused is only through postman and when I run my spring boot application in docker-compose, if i dont use docker-compose and I launch azurite in a terminal I am able to connect Storage Explorer to azurite and see the result when I upload a file, my spring boot application wraps file upload and download into APIs and uses docker-compose to launch my application with dependent services for azurite and postgres.  Let me know if this is still confuding.

**Comment by skanjila** [comment] 2022-11-09 17:38
Also this is not configuration/network issue in my local environment only as this behavior for docker compose is seen by all the engineers on my team

**Comment by skanjila** [comment] 2022-11-09 19:06
Also I tried to mimic the instructions in this readme:  https://github.com/Azure-Samples/automated-testing-with-azurite using docker-compose but was not able to run these python tests successfully

**Comment by skanjila** [comment] 2022-11-09 23:51
Finally @blueww this issue is similar to what I am facing:  https://github.com/Azure/Azurite/issues/715

**Comment by blueww** [comment] 2022-11-10 02:40
@skanjila 

Thanks for the update!
From you comments,  I get Storage Explorer and Postman target to Azurite start in different ways. 
Besides that, the 2nd issue of https://github.com/Azure/Azurite/issues/715 is caused by using a wrong IP (use "0.0.0.0" instead of "127.0.0.1"), which should be a different issue than you. 

I have tried the docker-compose from you, and I will always get following error when run "docker-compose up --build" with it.

> C:\azurite>docker-compose up --build
> [+] Building 5.4s (3/3) FINISHED
>  => [internal] booting buildkit                                                                                                                                                                                                                                                                                                                      5.4s
>  => => pulling image moby/buildkit:buildx-stable-1                                                                                                                                                                                                                                                                                                   4.6s
>  => => creating container buildx_buildkit_multi-platform-builder0                                                                                                                                                                                                                                                                                    0.7s
>  => [internal] load .dockerignore                                                                                                                                                                                                                                                                                                                    0.0s
>  => => transferring context: 2B                                                                                                                                                                                                                                                                                                                      0.0s
>  => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                                                 0.0s
>  => => transferring dockerfile: 2B                                                                                                                                                                                                                                                                                                                   0.0s
> failed to solve: failed to read dockerfile: open /tmp/buildkit-mount805901722/Dockerfile: no such file or directory

However, when I run ""docker-compose up" with docker-compose file [here](https://github.com/Azure/Azurite#docker-compose), it will always success and I can connect to Azurite after start it. (Let me know if this docker-compose file not work for you.)

As your docker-compose file is much more complex, this might be a docker-compose file configure issue. 
We own Azurite, but we are not docker-compose expert. So we might not be the best person for the complex docker compose file issues. 
I see there's a repo for docker compose, you might can raise your question there: https://github.com/docker/compose

BTW, the docker-compose in your before comment looks not in the right format, I format it as below, and please check it aligns with the docker-compose you are using.
```
version: '3.9'
services:
    web:
      build:
        context: .
        args:
          - ARTIFACTORY_API_TOKEN
          - ARTIFACTORY_USER
      depends_on:
        - db
        - azurite
      ports:
        - "8080:8080"
        - "4000:4000"
      environment:
        - ENVIRONMENT_NAME=local
        - REGION_NAME=local
        - AZURE_STORAGE_CONNECTION_STRING=mylocalconnectionstring
        - AZURE_STORAGE_CONTAINER=localcontainercreatedinstorageexplorer
       #- JVM_OPTIONS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=4000

    db:
      image: 'postgres:15-alpine3.16'
      container_name: db
      environment:
        - POSTGRES_USER=compose-postgres
        - POSTGRES_PASSWORD=compose-postgres
    azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      container_name: "azurite"
      hostname: azurite
      restart: always
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"
```

**Comment by skanjila** [comment] 2022-11-10 17:39
@blueww removing the web and db always works but that defeats the purpose of using spring boot with azurite and postgres which is what we're trying to accomplish, also the docker-compose file is indeed in the right format as my application wouldn't even launch otherwise, I pasted part of a docker-compose to you not the whole thing, the overall docker-compose is shown here:


# By default, you MUST run `make build` first before running `docker-compose up`
# Passing in `--build` or just simply running `docker-compose up` is not sufficient to
# build the container. See [ASR-3118](https://jira.corp.adobe.com/browse/ASR-3118) for more details.
version: '3.7'
services:
    web:
      build:
        context: .
        args:
          - ARTIFACTORY_API_TOKEN
          - ARTIFACTORY_USER
      depends_on:
        - db
        - azurite
      ports:
        - "8080:8080"
        - "4000:4000"
      environment:
        - ENVIRONMENT_NAME=local
        - REGION_NAME=local
        - AZURE_STORAGE_CONNECTION_STRING=replaceme
        - AZURE_STORAGE_CONTAINER=replaceme
  #     Uncomment this for enabling remote debugging option
  #     - JVM_OPTIONS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=4000

    db:
      image: 'postgres:15-alpine3.16'
      container_name: db
      environment:
        - POSTGRES_USER=compose-postgres
        - POSTGRES_PASSWORD=compose-postgres
    azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      hostname: azurite
      restart: always
      command: "azurite --blobHost 127.0.0.1 --blobPort 10000 --queueHost 127.0.0.1 --queuePort 10001"
      environment:
        - Azure__StorageConnectionString=localconnectionstring
      ports:
        - "10000:10000"
        - "10001:10001"

In the past I've built a docker-compose utility using mongodb and flask so this should be no different: https://github.com/ludwig-ai/model-hub/blob/main/docker-compose.yml

The whole point of docker compose is to mix and match different services that can be embedded into a web application

Thoughts?

**Comment by blueww** [comment] 2022-11-11 03:21
@skanjila

As the docker-compose file with only Azurite can work, it looks the issue is not caused by Azurite side, but by some issue in the other part of the docker-compose file.
Feel free to let me know if you see any evidence this is related with Azurite. 

Besides that, the Azurite command in the new docker-compose file is wrong, it should be `command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001"`, see more details in https://github.com/azure/azurite#run-azurite-v3-docker-image.
And it looks with the new docker-compose file, I will still get same error when run "docker-compose up --build" on my machine.

**Comment by blueww** [comment] 2022-12-01 05:23
@skanjila

I will close this issue as not hear from you for a long time.
Feel free to contact us again if need any further assistance on Azurite.

**Closed by blueww** 2022-12-01 05:23 UTC
Labels: question, docker
