### ISSUE TITLE
Content-MD5 should always be returned when listing blobs

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/Azurite#1592] opened 2022-07-08 17:32 UTC
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.14.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.13.1

### What problem was encountered?
When listing blobs, it occasionally return blobs without a Content-MD5 property in the XML response if the MD5 is empty. Maybe 
having an empty MD5 value is not the exact cause but that's my observation so far.

### Steps to reproduce the issue?
Upload an append blob to azurite instance with an empty MD5 value. Try to list the blob container which should return that blob.

In the response, the Content-MD5 property is missing.

Actual response:
```
<?xml version="1.0" encoding="utf-8"?>
<EnumerationResults ServiceEndpoint="" ContainerName="">
    <MaxResults>1000</MaxResults>
    <Delimiter>/</Delimiter>
    <Blobs>
        <Blob>
            <Name>blob</Name>
            <Properties>
                <Creation-Time>Thu, 11 Mar 2021 23:09:53 GMT</Creation-Time>
                <Last-Modified>Sat, 07 Aug 2021 00:19:39 GMT</Last…>
                <Content-CRC64 />
                <Cache-Control />
                <Content-Disposition />
                <BlobType>BlockBlob</BlobType>
                <AccessTier>Hot</AccessTier>
                <AccessTierInferred>true</AccessTierInferred>
                <LeaseStatus>unlocked</LeaseStatus>
                <LeaseState>available</LeaseState>
                <ServerEncrypted>true</ServerEncrypted>
            </Properties>
            <Metadata />
            <OrMetadata />
        </Blob>
    </Blobs>
    <NextMarker />
</EnumerationResults>
```

Expected response:
```
<?xml version="1.0" encoding="utf-8"?>
<EnumerationResults ServiceEndpoint="" ContainerName="">
    <MaxResults>1000</MaxResults>
    <Delimiter>/</Delimiter>
    <Blobs>
        <Blob>
            <Name>blob</Name>
            <Properties>
                <Creation-Time>Thu, 11 Mar 2021 23:09:53 GMT</Creation-Time>
                <Last-Modified>Sat, 07 Aug 2021 00:19:39 GMT</Last…>
                <Content-CRC64 />
                <Content-MD5/>   ------------------> This is missing
                <Cache-Control />
                <Content-Disposition />
                <BlobType>BlockBlob</BlobType>
                <AccessTier>Hot</AccessTier>
                <AccessTierInferred>true</AccessTierInferred>
                <LeaseStatus>unlocked</LeaseStatus>
                <LeaseState>available</LeaseState>
                <ServerEncrypted>true</ServerEncrypted>
            </Properties>
            <Metadata />
            <OrMetadata />
        </Blob>
    </Blobs>
    <NextMarker />
</EnumerationResults>
```

The public Azure blob service always returns the empty Content-MD5 in its list blob responses.

### Have you found a mitigation/solution?
People can manually parse the response and handle that. However, the @azure/storage-blob sdk currently cannot handle this situation because it uses NodeJS standard library to process that property value which will throw if the value is undefined. Due to that, such blob can cause the SDK to not be able to list any blobs if the response contains those problematic blobs.

**Comment by JasonYeMSFT** [comment] 2022-07-11 17:32
OK, thanks for sharing that. The error is about Node's crypto API expecting a string like argument but receives `undefined`. 
`The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined`.

We encountered this issue while using AzCopy to upload blob to Azurite. AzCopy sends and initial Put Blob request to create an empty blob at the destination and in the headers set the initial content-md5 to empty string. It then iteratively make Put Block List APIs to append the actual contents and finally set the content-md5 to the expected value. If we try to list blobs in Azurite when the content-md5 is still empty, the list response will contain `undefined` for content-md5. The SDK will attempt to parse it and fail.

I'll open an issue on the SDK repo and link to this issue. Since the public Azure service is not making the Content-Md5 optional, could you help double check if the API spec needs an update?

**Comment by blueww** [comment] 2022-07-12 06:47
> could you help double check if the API spec needs an update?
[Wei] in the [blob rest API doc](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs), it says 

> The Content-MD5 element appears in the response body only if it has been set on the blob using version 2009-09-19 or later. 

So I believe this is expected contentMD5 is not required.

**Comment by blueww** [comment] 2022-07-15 08:51
@JasonYeMSFT 

After I discuss with JS SDK owner, looks this is a fixed JS SDK issue.
Would you please check you are using the latest JS SDK?

**Comment by JasonYeMSFT** [comment] 2022-07-15 18:59
We are 1 version behind but I don't recall seeing anything related to that from the latest change log. I'll double check.

**Comment by DavidNorena** [comment] 2022-09-22 06:38
hi guys is there any progress on this ?

**Comment by blueww** [comment] 2022-09-22 09:58
@DavidNorena 
This is an js SDK issue, since SDK not aligned with rest API doc.
It should already been fixed in JS SDK.

**Comment by blueww** [comment] 2022-09-30 07:16
Close this issue as JS SDK is already fixed.

**Closed by blueww** 2022-09-30 07:16 UTC
Labels: question, blob-storage, alignment

**Comment by acmoune** [comment] 2023-01-22 10:36
Still having this issue with azurite v3.21.0

**Comment by DylanBruzenak** [comment] 2023-02-02 17:27
I also still have this issue in 3.21.0.

**Comment by blueww** [comment] 2023-02-03 01:43
@acmoune , @DylanBruzenak 

Please note the fix is in Js sdk, instead of Azurite.

Are you using the latest version of Azure Storage JS SDK?

**Comment by DylanBruzenak** [comment] 2023-02-08 17:28
@blueww I am using azure-storage-blob 12.12.0. Just created the project last week. Manually calculating the hashes does fix it: 

```
    const md5 = createHash('md5').update(blobContents).digest('hex')
    await blockClient.uploadStream(Readable.from(blobContents), blobContents.length, 5, {
      blobHTTPHeaders: { blobContentMD5: Buffer.from(md5, 'hex') },
    })
```

**Comment by blueww** [comment] 2023-02-09 02:46
@DylanBruzenak 

Would you please confirm which is the issue you meet with JS SDK 12.12.0 + Azurite 3.21.0?

1. You meet JS SDK failure as following in list blob, after upload a blob without set ContentMD5: 
`The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined.`
2. You don't meet JS SDK failure in list blob, but just expected the list out blob should return ContentMD5 value (or an empty Content MD5 header?), even if you don't set ContentMD5 in upload blob?

For 1, Per what I get from JS SDK owner, this should not happen on 12.12.0. If it still happen, would you please share your JS SDK code to repro the issue (hide credential if any) and Azure Debug log?
For 2, if user has not set ContentMD5 properties to a blob, the contentMD5 not return behavior is aligned with [blob rest API doc](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs), it says


> The Content-MD5 element appears in the response body, only if it has been set on the blob by using version 2009-09-19 or later.

**Comment by DylanBruzenak** [comment] 2023-02-10 20:21
I'm hitting #1. I cannot browse azurite using the latest version of the vs code plugin (Azurite v3.21.0), js SDK 12.12.0, and mcr.microsoft.com/azure-storage/azurite:latest for the docker image. Manually calculating the md5 and uploading it fixes it.

This is the code (modified slightly to remove some intermediate layers an:

app.ts:
```
import { ContainerClient } from '@azure/storage-blob'
import express from 'express'
import multer from 'multer'
import { Readable } from 'stream'

const CONNECTION_STRING = 'connection_string_goes_here'

const uploadBlob = async (blobName: string, blobContents: Buffer) => {
  const client = new ContainerClient(CONNECTION_STRING, 'files')
  const blockClient = client.getBlockBlobClient(blobName)

  await blockClient.uploadStream(Readable.from(blobContents), blobContents.length)
}

const v1Router = express.Router()

const uploadStrategy = multer({ storage: multer.memoryStorage() }).single('file')

v1Router.post('/file', uploadStrategy, async (req, res) => {
  const fileName = req.file?.originalname
  const fileBuffer = req.file?.buffer

  if (!fileName || !fileBuffer) {
    res.status(400).send('Missing fileName or fileBuffer')
    return
  }

  await uploadBlob(fileName, fileBuffer)

  res.end()
})

const app = express()

app.use('/v1', v1Router)

app.listen(3000, () => {
  console.log(`Listening on 3000`)
})
```

package.json:
```
{
  ...
  "dependencies": {
    "@types/express": "^4.17.16",
    "@types/multer": "^1.4.7",
    "@types/node": "18.11.10",
    "express": "^4.18.2",
    "multer": "^1.4.5-lts.1",
    "ts-node": "10.9.1",
    "typescript": "4.9.5",
  "@azure/identity": "^3.1.2",
  "@azure/storage-blob": "^12.12.0",
  },
}
```

You can curl this:
```curl -F 'file=ABSOLUTE_FILE_PATH' "localhost:3000/v1/file"```

After that browsing to this file in vscode displays the error string.

Changing uploadBlob to the example from my last post fixes it.

**Comment by blueww** [comment] 2023-02-14 06:50
@DylanBruzenak

How do you "browsing to this file in vscode"? 
As I know, the fix in JS SDK is: SDK won't fail when list blob when blob not has ContentMD5.

So it looks the problem is which app/sdk you use to  "browsing to this file in vscode"?  Do you use the latest app/SDK?

**Comment by DylanBruzenak** [comment] 2023-02-14 18:24
@blueww I am browsing to the file in the Azurite v3.21.0 VS Code plugin on the left bar.

**Comment by blueww** [comment] 2023-02-15 02:52
@DylanBruzenak 

I don't quite understand what do you mean by "browsing to the file in the Azurite v3.21.0 VS Code plugin on the left bar".
Azurite doesn't provide a browser to browse blobs in Azurite.

I think you might use other tools in VS code. Could you give the detail steps you use to browser the file (hide credential if any)?

**Comment by DylanBruzenak** [comment] 2023-02-15 03:29
Microsoft provides a va code plugin for azurite.  https://marketplace.visualstudio.com/items?itemName=Azurite.azurite
