### ISSUE TITLE
Azurite in Azure Devops Pipeline

### ISSUE THREAD

**Issue by asears** [Azure/Azurite#639] opened 2020-11-18 21:52 UTC
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.9.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What problem was encountered?

Emulator & C# XUnit test is working locally.  Test is failing in Devops pipeline.  Looking for minimal example of installing & testing that azurite blob emulator is functional in the agent, with TLS 1.2 and oauth basic.  Required for Azure SDK setup with DefaultCredential.

### Steps to reproduce the issue?
With an Azure Devops classic pipeline, windows-2019 agent I do the following.

1. download secure file pem (generated with mkcert locally on developer machine)
2. download secure file pem key
3. install azurite on the agent
'''bash
npm init -y
npm install -g azurite@3.9.0>&1
printenv
azurite --oauth basic --cert $(PEM_SECUREFILEPATH) --key $(KEY_SECUREFILEPATH) --loose -l /tmp --debug $(BUILD_ARTIFACTSTAGINGDIRECTORY)/debug.log &
```
4. minimal test task
```bash
curl 127.0.0.1:10000
curl localhost:10000
```
5. minimal test result devops
```plaintext

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   229  100   229    0     0  19083      0 --:--:-- --:--:-- --:--:-- 20818Path or Http-Method does not match any emulated command.
Possible causes include
  - missing account name path parameter
  - Unsupported Http-Method on resource
  - Unsupported / Not implemented "comp" query parameter on resource
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   229  100   229    0     0  38166      0 --:--:-- --:--:-- --:--:-- 45800Path or Http-Method does not match any emulated command.
Possible causes include
  - missing account name path parameter
  - Unsupported Http-Method on resource
  - Unsupported / Not implemented "comp" query parameter on resource
```

Happy path local test.

```bash
curl 127.0.0.1:10000
curl: (52) Empty reply from server
```
### Have you found a mitigation/solution?
No

**Comment by blueww** [comment] 2020-11-19 03:14
@asears
From the current information, we don't find obvious hint for this issue.
Would you please share the Azurite debug log, then we might can get more hints.

Besides that, we also test Azurite through Devops pipeline, you might can reference it: 
Config: https://github.com/Azure/Azurite/blob/master/azure-pipelines.yml
Oauth test case: https://github.com/Azure/Azurite/blob/master/tests/blob/oauth.test.ts

**Comment by chatchathu199162** [comment] 2022-02-11 16:48
I got the azurite for windows section but pipeline still failed
![image](https://user-images.githubusercontent.com/17563034/153632978-539ef76f-f8c3-49bf-b8d2-a0a3815d524d.png)

**Comment by chatchathu199162** [comment] 2022-02-11 17:32
this can be solved by following script
```
- task: NodeTool@0 
      inputs:
         versionSpec: 13.x
    - script : npm install -g azurite
      displayName: Install Azurite
    - script : start /B azurite
      displayName: Start azurite
```

**Comment by blueww** [comment] 2022-02-14 04:03
@chatchathu199162 
Good to know the issue is resolve on your side.
I will close this issue.

Feel free to contact us again if need any further assistance on Azurite.

**Closed by blueww** 2022-02-14 04:03 UTC
Labels: question, blob-storage, NewArch

**Comment by chatchathu199162** [comment] 2022-02-14 04:11
YesI will know if anything goes wrong , for now Pipeline is working
perfectly.
Thanks and regards
Chathurani
