### ISSUE TITLE
Possible TCP port conflict between Azurite and SWA Functions Host (VS Code)

### ISSUE THREAD

**Issue by LuKePicci** [Azure/Azurite#2376] opened 2024-03-08 12:11 UTC
### Which service(blob, file, queue, table) does this issue concern?
All

### Which version of the Azurite was used?
3.29.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS Code Extension

### What's the Node.js version?
any

### What problem was encountered?
starting azurite makes SWA CLI unable to start local functions host, functions host TCP port is busy and unavailable.

`[api] Port 7071 is unavailable. Close the process using that port, or specify another port using --port [-p].`

### Steps to reproduce the issue?
Start Azurite in VS Code and then use "SWA: Run xxxx" action from VS Code Run and Debug panel.

### Have you found a mitigation/solution?
If storage is not actually needed for debug, it is enough to Stop azurite, remove local storage emulator setting from local.settings.json and Click Cancel when Storage Account connection setup is prompted.
This is not viable for other projects where Storage Account emulation is needed.

**Comment by blueww** [comment] 2024-03-11 03:35
@LuKePicci 

Azurite by default listen on port 10000(Blob), 10001(Queue), 10002(Table).
You can change the port by set extension configuration: https://github.com/Azure/Azurite#:~:text=by%20default%20127.0.0.1-,azurite.blobPort,-Blob%20service%20listening

By default Azurite won't use port 7071.
And I have tested on my computer, after start Azurite service on VSCode, I still can listen on port 7071. 

So please check if there's any specific configuration/service on your computer which occupied 7071 port.

**Comment by LuKePicci** [comment] 2024-03-11 07:53
Nothing else is using port 7071, and as soon as I stop Azurite the error stops appearing. My best guess is that Azurite causes functions host to start twice. I dont know if the second instance is triggered by Azurite itself or by SWA CLI when Azurite is running.

**Comment by LuKePicci** [comment] 2024-03-11 07:53
Nothing else is using port 7071, and as soon as I stop Azurite the error stops appearing. My best guess is that Azurite causes functions host to start twice. I dont know if the second instance is triggered by Azurite itself or by SWA CLI when Azurite is running.

**Comment by LuKePicci** [comment] 2024-03-11 07:54
The same happens both on Windows and macOS with same VS code, Azurite and swa CLI versions.

**Comment by blueww** [comment] 2024-03-12 02:09
I am not familiar with SWA CLI, but I don't think Azurite can cause other function host to start. 
It might related with the way you start Azurite and SWA CLI.
Would you please give the detail how you start Azurite in VS code, and how to install SWA CLI and start SWA CLI. And is there any customized configuration on you computer on Azurite of SWA CLI. This might can help the investigation.

**Comment by blueww** [comment] 2024-03-14 03:49
@LuKePicci 

I will close this issue as it looks not caused by Azurite itself, and can't be fixed from Azurite code side.

Feel free to contact us again if need any further assistance on Azurite.

**Closed by blueww** 2024-03-14 03:49 UTC
Labels: question, vsc
