### ISSUE TITLE
Server failed to authenticate the request.

### ISSUE THREAD

**Issue by Karthickeyanofficial** [Azure/Azurite#233] opened 2019-06-24 15:59 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
3.0.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
8.11.2
### What problem was encountered?
Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature. RequestId:0974faae-06b9-4d87-b689-9a7e38a2e50f Time:2019-06-24T15:50:47.159Z

### Steps to reproduce the issue?
1. Install the azurite using npm install -g azurite and type the following in the address bar
http://127.0.0.1:10000/devstoreaccount1?comp=list

### Have you found a mitigation/solution?
No
[debug.log](https://github.com/Azure/Azurite/files/3321623/debug.log)

**Comment by XiaoningLiu** [comment] 2019-06-25 05:20
@Karthickeyanofficial This is expected in V3 as authentication is required to access resources. You can use any authentications types supported:
1. SharedKey (storage account name and key)
2. Shared Access Signature (SAS)
3. Public container or blob

**Comment by Karthickeyanofficial** [comment] 2019-06-25 08:28
we are using a shared key to access, 
AccountName=devstoreaccount1;
AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;
But we still get authentication issues. could you please help with this?

**Comment by ovuolteenaho** [comment] 2019-06-25 11:04
I'm also having a similar type of issue. The problem might be in the way Azurite creates the authentication string:

If I run a "List Containers" request against Azure with curl (the authorization header is wrong, which doesn't matter in this example):

```
curl http://127.0.0.1:10000/devstoreaccount1?comp=list -H "x-ms-date: Tue, 25 Jun 2019 10:12:43 GMT" -H "x-ms-version: 2018-03-28" -H "Authorization: this_is_obviously_not_real"
```
...Azurite's debug log shows it attempting to create the header:

```
2019-06-25T10:26:15.787Z 19f2e5f6-8d6c-4435-bb5d-3d9420b9ed1e info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-06-25T10:26:15.792Z 19f2e5f6-8d6c-4435-bb5d-3d9420b9ed1e info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-date:Tue, 25 Jun 2019 10:12:43 GMT\nx-ms-version:2018-03-28\n/devstoreaccount1/devstoreaccount1\ncomp:list"
2019-06-25T10:26:15.792Z 19f2e5f6-8d6c-4435-bb5d-3d9420b9ed1e info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:goIYZu1GGKb9SuMrQys2i2Jrrdkib+SvE6b/Tsvf6TQ=
2019-06-25T10:26:15.792Z 19f2e5f6-8d6c-4435-bb5d-3d9420b9ed1e info: BlobSharedKeyAuthenticator:validate() Validation failed.
```

This seems to show that the CanonicalizedResource part of the string is in the format "/devstoreaccount1/devstoreaccount1\ncomp:list" whereas according to MS documentation (https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key#Subheading2) the format should be "/devstoreaccount1\ncomp:list".

The possible problem seems to be in src/blob/authentication/BlobSharedKeyAuthenticator.ts:228

```
    canonicalizedResourceString += `/${account}${path}`;
```

...because both account and path would contain the account name, correct?

**Comment by XiaoningLiu** [comment] 2019-06-25 12:45
> I'm also having a similar type of issue. The problem might be in the way Azurite creates the authentication string:
> 
> If I run a "List Containers" request against Azure with curl (the authorization header is wrong, which doesn't matter in this example):
> 
> ```
> curl http://127.0.0.1:10000/devstoreaccount1?comp=list -H "x-ms-date: Tue, 25 Jun 2019 10:12:43 GMT" -H "x-ms-version: 2018-03-28" -H "Authorization: this_is_obviously_not_real"
> ```
> 
> ...Azurite's debug log shows it attempting to create the header:
> 
> ```
> 2019-06-25T10:26:15.787Z 19f2e5f6-8d6c-4435-bb5d-3d9420b9ed1e info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
> 2019-06-25T10:26:15.792Z 19f2e5f6-8d6c-4435-bb5d-3d9420b9ed1e info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-date:Tue, 25 Jun 2019 10:12:43 GMT\nx-ms-version:2018-03-28\n/devstoreaccount1/devstoreaccount1\ncomp:list"
> 2019-06-25T10:26:15.792Z 19f2e5f6-8d6c-4435-bb5d-3d9420b9ed1e info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:goIYZu1GGKb9SuMrQys2i2Jrrdkib+SvE6b/Tsvf6TQ=
> 2019-06-25T10:26:15.792Z 19f2e5f6-8d6c-4435-bb5d-3d9420b9ed1e info: BlobSharedKeyAuthenticator:validate() Validation failed.
> ```
> 
> This seems to show that the CanonicalizedResource part of the string is in the format "/devstoreaccount1/devstoreaccount1\ncomp:list" whereas according to MS documentation (https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key#Subheading2) the format should be "/devstoreaccount1\ncomp:list".
> 
> The possible problem seems to be in src/blob/authentication/BlobSharedKeyAuthenticator.ts:228
> 
> ```
>     canonicalizedResourceString += `/${account}${path}`;
> ```
> 
> ...because both account and path would contain the account name, correct?

@ovuolteenaho Thanks for debugging. Your last word is correct. It's by design to have 2 "duplicated" account name in the canonicalizedResourceString. This authentication behavior is aligned with Azure Storage SDKs with account key authentication.

**Comment by geethab** [comment] 2019-07-08 04:40
We got the same error while accessing a blob using a SAS Key. 
`Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature`

Was using nuget package `Microsoft.Azure.Storage.Blob` Version `10.0.3`
On further debugging found that we had to downgrade to Version `9.4`. This is because the access url with sas token had service-version `sv=2018-11-09` which was not supported by Azurite:latest. After the downgrade it was `sv=2018-03-28` and no longer got the Authentication error.

Would be great if Azurite could support the latest service version from Microsoft.Azure.Storage.Blob

**Comment by XiaoningLiu** [comment] 2019-07-08 06:48
@geethab Updating to 20181109 is on our roadmap. There is a SAS braking change in 2018-11-09. from 2018-11-09 all SAS supports snapshot parameter, this breaks previous SAS checking logic.

In the mean time, does Microsoft.Azure.Storage.Blob able to specific the API version when generate the SAS? For example, specficing the API version for the SAS generation method.

**Comment by geethab** [comment] 2019-07-09 09:20
Thank you @xiaoningliu. There was no option to provide the version explicitly. That's why downgraded.

**Comment by XiaoningLiu** [comment] 2019-07-10 03:01
Got it. @geethab BTW, can I know which scenario are you using Azurite for? Like testing or development? We recentaly got asks whether they can use Azurite as a on-premise object storage service for production, and we are now investigating how to further improve Azurite avaiability, relibility and performance to make it better.

**Comment by geethab** [comment] 2019-07-10 09:10
@xiaoningliu we are using it for local development to run unit and integration tests.

**Comment by matallanas** [comment] 2019-08-06 14:49
Hi, I am experimenting this issue with azurite in a docker. The generation of the SAS token was working, but today I cannot access to any file or download it since the SAS token has no authorization. Is there a new bug?
Thank you very much.

**Comment by XiaoningLiu** [comment] 2019-08-07 06:25
@matallanas Please enable debug log for Azurite and share with us. You can use following command. 

```cmd
docker run -p 10000:10000 -v c:/azurite:/workspace mcr.microsoft.com/azure-storage/azurite azurite -l /workspace -d /workspace/debug.log --blobPort 10000--blobHost 0.0.0.0
```

`c:/azurite` is an existing folder in **host**.

**Comment by matallanas** [comment] 2019-08-09 06:46
@XiaoningLiu I executed the docker with the log and it fails to create the authentication. Here I put the log I obtained.

`2019-08-08T21:54:09.222Z 288520af-9caa-4255-a4b6-ec9c335734ac verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-08-08T21:54:09.222Z 288520af-9caa-4255-a4b6-ec9c335734ac info: PublicAccessAuthenticator:validate() Start validation against public access.
2019-08-08T21:54:09.222Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: PublicAccessAuthenticator:validate() Getting account properties...
2019-08-08T21:54:09.222Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: landing, blob: example.csv
2019-08-08T21:54:09.222Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container landing
2019-08-08T21:54:09.222Z 288520af-9caa-4255-a4b6-ec9c335734ac info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-08-08T21:54:09.222Z 288520af-9caa-4255-a4b6-ec9c335734ac info: BlobSharedKeyAuthenticator:validate() Request doesn't include valid authentication header. Skip shared key authentication.
2019-08-08T21:54:09.223Z 288520af-9caa-4255-a4b6-ec9c335734ac info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.
2019-08-08T21:54:09.223Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: AccountSASAuthenticator:validate() Getting account properties...
2019-08-08T21:54:09.223Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: landing, blob: example.csv
2019-08-08T21:54:09.223Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: AccountSASAuthenticator:validate() Got account properties successfully.
2019-08-08T21:54:09.223Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: AccountSASAuthenticator:validate() Retrieved signature from URL parameter sig: wopnX3W5FpA17fCfKr8UwbdnhLqEQ+/eh0tvYW87Avk=
2019-08-08T21:54:09.224Z 288520af-9caa-4255-a4b6-ec9c335734ac info: AccountSASAuthenticator:validate() Failed to get valid account SAS values from request.
2019-08-08T21:54:09.224Z 288520af-9caa-4255-a4b6-ec9c335734ac info: BlobSASAuthenticator:validate() Start validation against blob service Shared Access Signature pattern.
2019-08-08T21:54:09.224Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: BlobSASAuthenticator:validate() Getting account properties...
2019-08-08T21:54:09.225Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: BlobSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: landing, blob: example.csv
2019-08-08T21:54:09.225Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: BlobSASAuthenticator:validate() Got account properties successfully.
2019-08-08T21:54:09.225Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: BlobSASAuthenticator:validate() Retrieved signature from URL parameter sig: wopnX3W5FpA17fCfKr8UwbdnhLqEQ+/eh0tvYW87Avk=
2019-08-08T21:54:09.225Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: BlobSASAuthenticator:validate() Signed resource type is b.
2019-08-08T21:54:09.225Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: BlobSASAuthenticator:validate() Successfully got valid blob service SAS values from request. {"version":"2018-03-28","startTime":"2019-08-09T06:23:31Z","expiryTime":"2019-08-10T06:23:31Z","permissions":"rl","containerName":"landing","blobName":"example.csv"}
2019-08-08T21:54:09.225Z 288520af-9caa-4255-a4b6-ec9c335734ac info: BlobSASAuthenticator:validate() Validate signature based account key1.
2019-08-08T21:54:09.226Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: BlobSASAuthenticator:validate() String to sign is: "rl\n2019-08-09T06:23:31Z\n2019-08-10T06:23:31Z\n/blob/devstoreaccount1/landing/example.csv\n\n\n\n2018-03-28\n\n\n\n\n"
2019-08-08T21:54:09.226Z 288520af-9caa-4255-a4b6-ec9c335734ac debug: BlobSASAuthenticator:validate() Calculated signature is: wopnX3W5FpA17fCfKr8UwbdnhLqEQ+/eh0tvYW87Avk=
2019-08-08T21:54:09.226Z 288520af-9caa-4255-a4b6-ec9c335734ac info: BlobSASAuthenticator:validate() Signature based on key1 validation passed.
2019-08-08T21:54:09.226Z 288520af-9caa-4255-a4b6-ec9c335734ac info: BlobSASAuthenticator:validate() Validate start and expiry time.
2019-08-08T21:54:09.226Z 288520af-9caa-4255-a4b6-ec9c335734ac info: BlobSASAuthenticator:validate() Validate start and expiry failed.
2019-08-08T21:54:09.227Z 288520af-9caa-4255-a4b6-ec9c335734ac error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2019-08-08T21:54:09.228Z 288520af-9caa-4255-a4b6-ec9c335734ac error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.  ErrorHTTPStatusCode=403 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"288520af-9caa-4255-a4b6-ec9c335734ac"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:288520af-9caa-4255-a4b6-ec9c335734ac\nTime:2019-08-08T21:54:09.226Z</Message>\n</Error>" ErrorStack="StorageError: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\n    at Function.getAuthorizationFailure (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:83:16)\n    at BlobSASAuthenticator.validate (/opt/azurite/dist/src/blob/authentication/BlobSASAuthenticator.js:104:49)\n    at AuthenticationMiddlewareFactory.authenticate (/opt/azurite/dist/src/blob/authentication/AuthenticationMiddlewareFactory.js:34:40)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-08-08T21:54:09.228Z 288520af-9caa-4255-a4b6-ec9c335734ac error: ErrorMiddleware: Set HTTP code: 403
2019-08-08T21:54:09.228Z 288520af-9caa-4255-a4b6-ec9c335734ac error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=AuthorizationFailure
2019-08-08T21:54:09.229Z 288520af-9caa-4255-a4b6-ec9c335734ac error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=288520af-9caa-4255-a4b6-ec9c335734ac
2019-08-08T21:54:09.229Z 288520af-9caa-4255-a4b6-ec9c335734ac error: ErrorMiddleware: Set content type: application/xml
2019-08-08T21:54:09.229Z 288520af-9caa-4255-a4b6-ec9c335734ac error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:288520af-9caa-4255-a4b6-ec9c335734ac\nTime:2019-08-08T21:54:09.226Z</Message>\n</Error>"
2019-08-08T21:54:09.229Z 288520af-9caa-4255-a4b6-ec9c335734ac info: EndMiddleware: End response. TotalTimeInMS=8 StatusCode=403 StatusMessage=Forbidden Headers={"server":"Azurite-Blob/3.1.2-preview","x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"288520af-9caa-4255-a4b6-ec9c335734ac","content-type":"application/xml"}
2019-08-08T21:54:09.407Z e40f58e8-1402-4080-9adb-3dcf4acfbc60 info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/favicon.ico RequestHeaders:{"host":"127.0.0.1:10000","connection":"keep-alive","sec-fetch-mode":"no-cors","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36","accept":"image/webp,image/apng,image/*,*/*;q=0.8","sec-fetch-site":"same-origin","referer":"http://127.0.0.1:10000/devstoreaccount1/landing/example.csv?st=2019-08-09T06%3A23%3A31Z&se=2019-08-10T06%3A23%3A31Z&sp=rl&sv=2018-03-28&sr=b&sig=wopnX3W5FpA17fCfKr8UwbdnhLqEQ%2B%2Feh0tvYW87Avk%3D","accept-encoding":"gzip, deflate, br","accept-language":"es-ES,es;q=0.9,en;q=0.8,gl;q=0.7"} ClientIP=172.17.0.1 Protocol=http HTTPVersion=1.1
2019-08-08T21:54:09.407Z e40f58e8-1402-4080-9adb-3dcf4acfbc60 info: BlobStorageContextMiddleware: Account=favicon.ico Container=undefined Blob=
2019-08-08T21:54:09.407Z e40f58e8-1402-4080-9adb-3dcf4acfbc60 verbose: DispatchMiddleware: Dispatching request...
2019-08-08T21:54:09.408Z e40f58e8-1402-4080-9adb-3dcf4acfbc60 error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2019-08-08T21:54:09.408Z e40f58e8-1402-4080-9adb-3dcf4acfbc60 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2019-08-08T21:54:09.408Z e40f58e8-1402-4080-9adb-3dcf4acfbc60 error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at Object.dispatchMiddleware [as default] (/opt/azurite/dist/src/blob/generated/middleware/dispatch.middleware.js:41:30)\n    at /opt/azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:49:42\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:317:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:275:10)\n    at blobStorageContextMiddleware (/opt/azurite/dist/src/blob/context/blobStorageContext.middleware.js:51:5)\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:317:13)"
2019-08-08T21:54:09.408Z e40f58e8-1402-4080-9adb-3dcf4acfbc60 error: ErrorMiddleware: Set HTTP code: 400
2019-08-08T21:54:09.408Z e40f58e8-1402-4080-9adb-3dcf4acfbc60 error: ErrorMiddleware: Set HTTP body: undefined
2019-08-08T21:54:09.408Z e40f58e8-1402-4080-9adb-3dcf4acfbc60 info: EndMiddleware: End response. TotalTimeInMS=1 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.1.2-preview"}`

**Comment by XiaoningLiu** [comment] 2019-08-12 02:42
Hi @matallanas According to log your shared. The `startTime` in your SAS is not valid. 

Start & expiryTime in your SAS:
"startTime":"2019-08-09T06:23:31Z","expiryTime":"2019-08-10T06:23:31Z"

Request time:
2019-08-08T21:54:09.226Z

**Comment by gorillapower** [comment] 2019-08-15 07:45
We are also experiencing this issue when referencing Azurite from a Durable Function locally.

**Comment by XiaoningLiu** [comment] 2019-08-15 09:50
> We are also experiencing this issue when referencing Azurite from a Durable Function locally.

@gorillapower Please share debug.log for investigation too.

**Comment by sarink** [comment] 2019-08-26 13:47
Is there any update or workaround to this? If you can't access uploaded files... Then this renders the entire emulator completely useless? I'm very confused why this hasn't been fixed yet.

**Comment by XiaoningLiu** [comment] 2019-08-27 01:19
@sarink Sorry for the inconvenience. Please use SharedKey authentication. Or using previous version SDKs before SAS generation logic breaking (SDK version before upgrading to Azure Storage API Version 2018-11-09).

**Comment by sarink** [comment] 2019-08-27 05:34
@XiaoningLiu how do I use SharedKey authentication? I am connecting via connection string from the readme https://github.com/Azure/Azurite#connection-string

Or, how would I downgrade, and which version would I select? I'm using the docker container https://hub.docker.com/_/microsoft-azure-storage-azurite but the only published tag seems to be available is `latest`?

**Comment by XiaoningLiu** [comment] 2019-08-28 01:54
@sarink If you are using following connection string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;" it means you already use SharedKey authentication. Please share Azurite's debug.log if the autentication still fails.

Downgrade SDK you are using instead of Azurite. Latest SDK version has a breaking change which makes the SAS token generated by latest SDKs cannot pass through Azurite's authenitcation. For example, if you are using Azure Storage JavaScript SDK @azure/storage-blob 10.4.0, you can revert back to 10.3.0. The breaking change happens when SDK updates to Azure Storage API Version 2018-11-09. You can find out when the breaking change happens in which SDK version in SDK's changelog.

https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-blob/ChangeLog.md

**Comment by mattiasflodin** [comment] 2019-11-11 10:19
I realize that it can be hard to find the time to track changes in the underlying API, and it's very clear in the README.md what versions are supported. But, being new to Azure, I had not expected that an API that has been around for so long would not even be able to authenticate to Microsoft's recommended simulator. I didn't even think to check the supported versions. I'm using Microsoft's Java SDK and none of the packages provided in the repositories support the older API version that Azurite provides. The error messages are pretty obscure - nothing in the default output, and the debug log seems to blame swagger (which I haven't used since I'm not a JS developer, so that's also cryptic to me).

So I'd like to recommend that until this works, it would be made even more clear. Perhaps some boldface text at the top of the readme saying "**Note that the latest versions of the Azure API do _not_ work. Please verify the API version that your client library is using against this table.**"

**Comment by XiaoningLiu** [comment] 2019-11-12 08:00
@all The server authentication issue should have been fixed by the latest released 3.3.0-preview or latest version. Will close this issue.

@mattiasflodin Thanks for your suggestion! It make sense to improve the logging errors. For your debug log, it's not because of wrong API version. Your URL pattern is not correct, "http://127.0.0.1/$root/datafile", that's why Azurite complains about URL pattern issue. The correct url pattern is like "http://127.0.0.1/devstoreaccount1/$root/datafile".

It's true Azurite won't support all storage features. Some features are not suitable to be provided in a Azurite as lightweight local service, and some Azure storage features depend on other Azure services. We will give a clear list for supported features in Azurite readme.

**Closed** 2020-01-02 07:36 UTC
Labels: NewArch, featureparity, question, v3.3

**Comment by KPGDL** [comment] 2022-04-11 07:15
Doesn't seems to be fixed - my SAS token generated by Azure .NET SDK doesn't get authenticated.
`<PackageReference Include="Azure.Storage.Blobs" Version="12.11.0" />`

**Comment by blueww** [comment] 2022-04-11 07:40
@KPGDL 
This should be another issue tracked in https://github.com/Azure/Azurite/issues/1404.
