### ISSUE TITLE
Create a blob inside not existing folder break Azurite

### ISSUE THREAD

**Issue by gabrielef** [Azure/Azurite#259] opened 2019-09-20 09:52 UTC
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.2.0-preview

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v8.16.1

### What problem was encountered?
If I try to create a blob inside a folder that doen't exist I receive a success result code, but azurite blob containers are no longer available with message: 
_Unable to retrieve child resources. Container name format is incorrect._

### Steps to reproduce the issue?
Create a blob inside a container with missing folder.

create file container1/folder-not-exist/fila.json

### Have you found a mitigation/solution?
Yes, the only way is to stop azurite, delete the file __azurite_db_blob__.json, start azurite
This solve the problem, but you will lose all blob containers.

**Comment by XiaoningLiu** [comment] 2019-09-24 09:50
Hi @gabrielef Thanks for reporting. So the error is from storage explorer right? Will check this before our next release.

**Comment by gabrielef** [comment] 2019-09-24 10:45
Hi @XiaoningLiu, yes the error is from Microsoft Storage Explorer.

**Comment by XiaoningLiu** [comment] 2019-11-07 05:37
@gabrielef I cannot reproduce this. Steps are:

1. Client "New Folder" button in Storage Explorer and enter a folder name "folder" and click "OK"
2. Upload a file to the folder
3. Refresh the container and list blobs under tha container

![image](https://user-images.githubusercontent.com/6889160/68362849-ab90b900-0163-11ea-9b20-bbe4386572cf.png)

**Comment by XiaoningLiu** [comment] 2019-11-12 08:25
Hi @gabrielef Please try with latest released 3.3.0-preview. Welcome to re-open the issue if the issue exists and can be reproduced. Will close this issue.

**Closed** 2020-01-02 03:34 UTC
Labels: triage, v3.3
