### ISSUE TITLE
Go SDK returning unexpected EOF when using batch insert mode

### ISSUE THREAD

**Issue by davidandradeduarte** [Azure/Azurite#1378] opened 2022-03-08 00:16 UTC
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.16.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
When using batch insert mode with the Go SDK, we get an `unexpected EOF`. This is probably related with the way the SDK handles either the batch HTTP request or response.
An issue in the SDK repo was already created, but I'm opening an issue here in hopes that someone knows what's wrong from the debug logs.
There are two batch requests in the logs. The first one comes from a C# SDK client and the second one from a Go SDK client. The C# SDK seems to handle it properly, the Go SDK doesn't.
**Azurite debug logs**: https://github.com/davidandradeduarte/azurite-insert-batch-bugs/blob/main/azurite-logs/batch-csharp-vs-go.log
**SDK issue**: https://github.com/Azure/azure-sdk-for-go/issues/14750

### Steps to reproduce the issue?
The repro code is available at:
https://github.com/davidandradeduarte/azurite-insert-batch-bugs
Both C# and Go clients are included, as well as the Azurite debug log.

### Have you found a mitigation/solution?
I've tried to compare the HTTP request/response logs from both SDKs, but can't figure out what's wrong.

**Comment by XiaoningLiu** [comment] 2022-03-09 10:30
Interesting C# works while Go client doesn't with same Azurite batch response.

**Comment by davidandradeduarte** [comment] 2022-03-09 12:50
> Interesting C# works while Go client doesn't with same Azurite batch response.

Yeah, it is odd.
This might be a duplicate of https://github.com/Azure/Azurite/issues/1381, but I'm keeping it open since you'll have logs for both clients in this issue. Might be easier to spot the difference between a client that works and one that doesn't.

**Comment by edwin-huber** [comment] 2022-03-23 09:09
The EOF error is caused by changes made #1079 , where we removed a final CRLF due to issues with the Cosmos Table SDK, as seen in #1002.  
At the time, all other SDKs were fine with this change.  
As the service responds with 3 CRLFs (\r\n\r\n\r\n) before the closing of the changesetresponse section, I would revert to the response format used by the service.
 https://github.com/azure/azurite/blob/c9aac3027d6403ad7a8cede3b38cb471f42cf20a/src/table/batch/TableBatchOrchestrator.ts#L136
 ```typescript
     const changesetBoundaryClose: string = "--" + changesetBoundary + "--\r\n";
```
 will become
 ```typescript
     const changesetBoundaryClose: string =
      "\r\n--" + changesetBoundary + "--\r\n";
  ```

PR inbound

**Closed** 2022-03-24 08:12 UTC
Labels: table-storage, NewArch, investigation, table-batch
