### ISSUE TITLE
Blob: Request hangs, does not return when uploading blob

### ISSUE THREAD

**Issue by robertsundstrom** [Azure/Azurite#798] opened 2021-05-31 18:55 UTC
### Which service(blob, file, queue, table) does this issue concern?

Blob

### Which version of the Azurite was used?

Docker:
mcr.microsoft.com/azure-storage/azurite (edit)

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub

### What's the Node.js version?

Running in Docker container.

### What problem was encountered?

When uploading a blob using the Azure Blob Storage Client API, the request just hangs. It is not finishing, nor returning. Awaiting forever. 

This is a recurring. It feels like a lottery to get this to work.

### Steps to reproduce the issue?

```c#
 var response = await blobContainerClient.UploadBlobAsync(name, stream, cancellationToken);
```

### Have you found a mitigation/solution?

Nope

**Comment by blueww** [comment] 2021-06-01 03:17
@robertsundstrom 
The docker image you use seems is not correct :  `mcr.microsoft.com/azure-sql-edge:latest`

The correct docker image is: `mcr.microsoft.com/azure-storage/azurite`

You can find more details in: https://github.com/Azure/Azurite#dockerhub
If you still meet issue, would you please check if the docker image is started correctly, and share the connection string you use to connect to Azurite, and attach the debug log.

**Comment by robertsundstrom** [comment] 2021-06-01 06:12
@blueww I see. I copied the wrong name;  mcr.microsoft.com/azure-storage/azurite [Source](https://github.com/robertsundstrom/xamarin-forms-app/blob/main/tye.yaml)

I run on a M1 Mac.

**Comment by blueww** [comment] 2021-06-01 06:28
@robertsundstrom

Would you please share the above information that required?
And please add the Azurite version, and the command you use to run Azurite.

**Comment by robertsundstrom** [comment] 2021-06-02 19:06
Tye launches it in Docker using this command:

```
[azurite_e1720e9e-4]: docker run -d -v "/Users/robert/Projects/ShellApp/.data/azurite:/data:z" -e "PORT=10000;10001;10002" -e "PROXY_PORT=10000:10000;10001:10001;10002:10002" -e "SERVICE__AZURITE__BLOB__PROTOCOL=http" -e "AZURITE_BLOB_SERVICE_PROTOCOL=http" -e "SERVICE__AZURITE__BLOB__PORT=10000" -e "AZURITE_BLOB_SERVICE_PORT=10000" -e "SERVICE__AZURITE__BLOB__HOST=host.docker.internal" -e "AZURITE_BLOB_SERVICE_HOST=host.docker.internal" -e "SERVICE__AZURITE__QUEUE__PROTOCOL=http" -e "AZURITE_QUEUE_SERVICE_PROTOCOL=http" -e "SERVICE__AZURITE__QUEUE__PORT=10001" -e "AZURITE_QUEUE_SERVICE_PORT=10001" -e "SERVICE__AZURITE__QUEUE__HOST=host.docker.internal" -e "AZURITE_QUEUE_SERVICE_HOST=host.docker.internal" -e "SERVICE__AZURITE__TABLE__PROTOCOL=http" -e "AZURITE_TABLE_SERVICE_PROTOCOL=http" -e "SERVICE__AZURITE__TABLE__PORT=10002" -e "AZURITE_TABLE_SERVICE_PORT=10002" -e "SERVICE__AZURITE__TABLE__HOST=host.docker.internal" -e "AZURITE_TABLE_SERVICE_HOST=host.docker.internal" -e "SERVICE__SHELLAPP-WEB__PROTOCOL=https" -e "SHELLAPP-WEB_SERVICE_PROTOCOL=https" -e "SERVICE__SHELLAPP-WEB__PORT=5020" -e "SHELLAPP-WEB_SERVICE_PORT=5020" -e "SERVICE__SHELLAPP-WEB__HOST=host.docker.internal" -e "SHELLAPP-WEB_SERVICE_HOST=host.docker.internal" -e "CONNECTIONSTRINGS__MSSQL=Server=host.docker.internal,1433;User Id=sa;Password=P@ssw0rd" -e "APP_INSTANCE=azurite_e1720e9e-4" -e "CONTAINER_HOST=host.docker.internal" -p 10000:10000 -p 10001:10001 -p 10002:10002 --name azurite_e1720e9e-4 --restart=unless-stopped --network tye_network_78bc8052-3 --network-alias azurite mcr.microsoft.com/azure-storage/azurite
[azurite_e1720e9e-4]: WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[azurite_e1720e9e-4]: 612a4bb0047c487d2aa4be9b104e248f8bcd76f309c49984aebc2d93fa2bc5fe
[azurite_e1720e9e-4]: Azurite Blob service is starting at http://0.0.0.0:10000
[azurite_e1720e9e-4]: Azurite Blob service is successfully listening at http://0.0.0.0:10000
[azurite_e1720e9e-4]: Azurite Queue service is starting at http://0.0.0.0:10001
[azurite_e1720e9e-4]: Azurite Queue service is successfully listening at http://0.0.0.0:10001
[azurite_e1720e9e-4]: Azurite Table service is starting at http://0.0.0.0:10002
[azurite_e1720e9e-4]: Azurite Table service is successfully listening at http://0.0.0.0:10002
```

**Comment by blueww** [comment] 2021-06-07 09:25
@robertsundstrom

You have shared the command to start Azurite and the log.
Would you please share the other necessary information include:
1. Azurite version
2. share the connection string you use to connect to Azurite (by default parameters, you can use the connection string in https://github.com/Azure/Azurite#http-connection-strings).

From the log, it seems your client didn't connect to Azurite.
And when I start Azurite docker with similar command with you (remove "-v "/Users/robert/Projects/ShellApp/.data/azurite:/data:z" and "--network tye_network_78bc8052-3"), it work well on my machine.
Please check the connection string you use in client is correct. and why you add the above --network parameter?

**Comment by robertsundstrom** [comment] 2021-06-07 18:49
I run on an M1 Mac, and I don't know if that affects something. I do get a warning because of "Unsupported architecture"

I run Azurite in Docker, using Microsoft Tye to orchestrate all services. The tools ad it to a network.

As I said earlier. It seems to me that it just locks the request is being made and never returns.

Azurite Version (in the container): 3.12.0

Connection string: ```DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;```

**Comment by blueww** [comment] 2021-06-08 05:45
@robertsundstrom 

From the behavior and the log you give, it looks the client doesn't access Azurite port.
The way your start Azurite (with "--network tye_network_78bc8052-3") might make the "http://127.0.0.1:10000" does not work.
You can check by open "http://127.0.0.1:10000" in network explorer:
 -  if any error with code and message appear, means the address is accessible
 -  if just says can't reach the page, means the address is not accessible.

If the page is not accessible, please try to start Azurite with the simple command like following, to see if the issue is resolved.
`docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite`

**Comment by loune** [comment] 2021-11-13 22:11
I had the same issue with Azurite and the JS SDK `@azure/storage-blob`. When I call `await blockBlobClient.uploadStream(source...` it never returns and stays frozen. I turned on the Azurite debug log and found this error message:
```
2021-11-13T21:51:53.991Z 8b17e03d-7149-41e4-807c-097e957e21dc error: ErrorMiddleware: Set HTTP code: 500
2021-11-13T21:51:53.992Z 8b17e03d-7149-41e4-807c-097e957e21dc error: ErrorMiddleware: Set HTTP status message: x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter "--loose" or Visual Studio Code configuration "Loose". Please vote your wanted features to https://github.com/azure/azurite/issues
2021-11-13T21:51:53.992Z 8b17e03d-7149-41e4-807c-097e957e21dc error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=FeatureNotSupported
```
When I ran Azurite with `--loose` the problem went away.

For some reason between the SDK and Azurite, the `500` error server response is not received or acknowledged by the client. Not sure if it matters but I have an M1 mac as well.

**Comment by blueww** [comment] 2021-11-15 02:55
@loune 
You issue is the same as https://github.com/Azure/Azurite/issues/676 for "x-ms-encryption-algorithm" support. Looks different than the originally one. Using "--loose" currently is the way to workaround it.

Normally SDK should can handle the 500 error. If SDK can't handle is correctly and hang, you can contact SDK for the issue.

**Comment by robertsundstrom** [comment] 2021-11-17 22:45
The ```--loose``` flag seems to have resolved my issue. It. does not hang anymore.

This is my current ```tye.yaml```:

```
name: webapi
services:
- name: webapi
  project: WebApi.csproj
  bindings:
  - protocol: https
    port: 5020

- name: azurite
  image: mcr.microsoft.com/azure-storage/azurite
  args: "azurite-blob --loose --blobHost 0.0.0.0"    # This solved it
  bindings:
    - name: blob
      port: 10000
      containerPort: 10000
      protocol: http
    - name: queue
      port: 10001
      containerPort: 10001
      protocol: http
    - name: table
      port: 10002
      containerPort: 10002
      protocol: http
  volumes:
    - source: .data/azurite
      target: /data
```

**Comment by blueww** [comment] 2021-11-18 03:21
@robertsundstrom
Good to know the hang issue is resolved on your side.
As we already have another issue  #676 to track "x-ms-encryption-algorithm" support, would you like to close this issue?

For the default location, as this is another issue, would you like to open a new issue and give the details for the expected behavior? We have another location related issue https://github.com/Azure/Azurite/issues/756, is your issue related with this one?

**Closed** 2021-11-18 14:00 UTC
Labels: question, blob-storage, NewArch
