### ISSUE TITLE
Customized storage accounts for Azurite with Azure Functions project in VS not working

### ISSUE THREAD

**Issue by noontz** [Azure/Azurite#2018] opened 2023-06-24 11:45 UTC
### Which service(blob, file, queue, table) does this issue concern?
Accounts - blob

### Which version of the Azurite was used?
3.22.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio Code Extension (VS 17.6.4)

### What's the Node.js version?
18.13.0

### What problem was encountered?
Customized storage accounts for Azurite on local windows are not working

### Steps to reproduce the issue?
[Follow the documentation](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio#custom-storage-accounts-and-keys)

Run
`BlobServiceClient serviceClient = new BlobServiceClient("myCustomConnectionString");`
`BlobContainerClient containerClient = serviceClient.GetBlobContainerClient("mycontainer");`
`await containerClient.CreateIfNotExistsAsync();` 

Throws an exception "Invalid storage account".

### Have you found a mitigation/solution?
No..  [I have raised a question on SO](https://stackoverflow.com/questions/76541757/customized-storage-account-for-azurite-on-local-windows-not-working), but I have not received any answers

**Comment by blueww** [comment] 2023-06-26 05:56
@EmmaZhu 
Would you please help to look at this issue?

**Comment by noontz** [comment] 2023-06-26 12:37
It seems like this issue is not constrained to VS and Azure Functions.  I tried to run Azurite from console, with custom accounts as per the documentation, and the same exception is thrown from the Microsoft Azure Storage Explorer when trying to access the Blob Containers. Is there any way to list what account(name)s Azurite is hosting through the console?

**Comment by noontz** [comment] 2023-06-26 13:10
One thing I notice is that the authorization header:
`"authorization":"SharedKey imageaccount:u7YccKeqWvr02W1L64LBkYEsCv5PLG8w/HCiRGyzoqQ="`
Does not match my environment entry:
`AZURITE_ACCOUNTS="imageaccount:SU1BR0VfQkxPQl9TVE9SQUdFX1VSTA==;poiaccount:UE9JX0JMT0JfU1RPUkFHRV9VUkw="`

**Comment by blueww** [comment] 2023-06-28 07:22
@noontz 

Would you like try to set the enviroment without `"` ?
Like `set AZURITE_ACCOUNTS=imageaccount:SU1BR0VfQkxPQl9TVE9SQUdFX1VSTA==`.
This works in my testing.

Besides that, the authorization header is a signature constructed from the request. It's not the sharedkey itself. So the values are different.
see more details in https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key#specifying-the-authorization-header

**Comment by noontz** [comment] 2023-06-28 10:41
@blueww Not using the quotation marks work, if I start a separate command window (as administrator), set the environment variable without quotation marks, and start Azurite.
That said it has not been possible for me to start Azurite automatically from VS, and pickup the environment variables correctly. The exception persists in this context. I have tried to use both the Developer Command Prompt and a separate Command Window. There might be other opportunities I am unaware of.
Clearly the documentation needs to be updated, to reflect this, and if it is possible to somehow pass the environment variables to the Azurite process running inside VS, this should also be  clearly documented. (It should also be documented if it is NOT possible)..  I will post an answer on the SO thread.   Thanks for your efforts 👍

**Comment by blueww** [comment] 2023-06-29 08:49
@noontz 

Thanks for the update!
It's good to know the customized account works for your now.

For Azurite start from VS not work with Environment variable, this do work for me. 
Not sure if the failure on your side caused by: you set the Environment variable in one command console, then start VS separately ( not from the command console has the environment variable). You can try to start VS from same command console after set the environment variable.
There's another way, you can set enviroment variable in [this way](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0), then start VS, and then see if Azurite will take the environment variable.

@EmmaZhu, Would you please help to check why current Doc has " for set the environment variables of customized account, and see if need update it?

**Comment by noontz** [comment] 2023-06-30 09:56
@blueww Yes.  Adding the setting manually to the windows system variables (without quotation marks) also works. In this way the variables are picked up Azurite independent of hosting (vs or console). I have updated the answer on SO accordingly. Thank you!

**Comment by blueww** [comment] 2023-07-03 03:44
Discussed with Xiaoning:
There are several ways to fix the doc:
1. Remove " in the 2 [samples ](https://github.com/Azure/Azurite#customized-storage-accounts--keys)
2. Using `setx AZURITE_ACCOUNTS "account1:key1"` per doc: http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-windows-command-line-and-registry/ (The setting won't take effect in current window, but only on following opened window)
3. Removing [2 samples](https://github.com/Azure/Azurite#customized-storage-accounts--keys) , only left description for environment variable name and value.

We will choose 1 first, then might adjust per further customer feedback.

**Comment by blueww** [comment] 2023-09-15 01:58
The doc fix PR is merged, so close this issue.

**Closed by blueww** 2023-09-15 01:58 UTC
Labels: question, blob-storage

**Comment by csleight-iinkedSign** [comment] 2024-06-28 00:20
Documentation still shows the quotes.

```
set AZURITE_ACCOUNTS="account1:key1"
```

![image](https://github.com/Azure/Azurite/assets/173306251/2cbb5801-e743-4803-92b5-c4f228e3de6a)


https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=visual-studio%2Cblob-storage#custom-storage-accounts-and-keys
