### ISSUE TITLE
Attaching Azure Storage Explorer to remote Azurite Docker image ?

### ISSUE THREAD

**Issue by markddrake** [Azure/Azurite#538] opened 2020-08-23 01:46 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
docker/latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Dockerhub

### Steps to reproduce the issue?
Started Docker Image on Remote Docker Host machine with 

```
docker run -p 10000:10000 -d --name AZURE-91 mcr.microsoft.com/azure-storage/azurite  azurite-blob --blobHost 0.0.0.0 --blobPort 10000. 
```
Using the browser to connect to http:/192.168.1.250:10000 gives me

```
<Error>
<script/>
<Code>InvalidQueryParameterValue</Code>
<Message>Value for one of the query parameters specified in the request URI is invalid. RequestId:bf7355cf-c1cf-4e12-8e8e-e796c65665af Time:2020-08-23T01:38:49.247Z</Message>
</Error>
```
So I think this means something (Azurite I assume) is listening on that port and accessible from my laptop.

Trying to get Azure Storage Explorer connected, but being new to this and at a bit of a lost... If I select attach to a local emualator it appears to assume that the emulator is literally running locally.

If I try and use a connection string such as 
```
DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;
AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;
BlobEndpoint=http://192.168.1.250:10000/devstoreaccount1;
```
I get the following in the Attach with Connection String dialog..

```
!The connection string is missing an account key or SAS token.
```
At this point I'm out of ideas...

**Comment by blueww** [comment] 2020-08-24 04:12
@markddrake 
Thanks for raising the issue!

For Connection string, please remove the space, and line change char in the connection string and try again:
```
DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://192.168.1.250:10000/devstoreaccount1;
```

For the error with "InvalidQueryParameterValue"
Would you like to provide the Azurite debug log for it?

**Comment by hholst80** [comment] 2022-01-05 18:37
@markdrake were you able to fix this? did the hint by blueww resolve the issue, or was there anything else that caused your connection to fail?

**Comment by markddrake** [comment] 2022-01-09 17:21
@hholst80: I was able to connect using the info from @blueww

**Comment by blueww** [comment] 2022-01-10 03:00
@markddrake 
Good to know the issue is resolved on your side.
I will close this issue.

Feel free to contact us again if you need any assistance on Azurite.

**Closed by blueww** 2022-01-10 03:00 UTC
Labels: question, blob-storage, NewArch

**Comment by 4vadim4** [comment] 2022-01-19 13:39
@markddrake , hi, maybe you can help,
a have the same problem: after started azurite image in docker container i try to connect in browser **http://localhost:10000** but i get an error "**InvalidQueryParameterValue**",
i.e. i need query parameters in url: DefaultEndpointsProtocol, AccountName, AccountKey etc, but why ? 
I use a local emulator - Azurite, which shouldn't know anything about real Azur Storage credentials. Why should i enter them here? If not then where i should get them for local use?
How did you solve this problem?
p.s.: My case: i have docker container with app and i want to have azurite storage in separate docker container which can upload, give and delete data on request from the first container with app. All this using python.

**Comment by smargoli2** [comment] 2024-01-22 11:10
I'm having a similar issue to this.
I can run `docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite`
but when I try to run just the table storage like this `docker run -p 10002:10002 mcr.microsoft.com/azure-storage/azurite azurite-table --tableHost 127.0.0.1 --tablePort 10002`
 it does not print out 'Azurite Table service is successfully listening at http://0.0.0.0:10002', it just says successfully started, and I cannot connect to it in the Azure Storage Explorer app.

**Comment by EmmaZhu** [comment] 2024-01-23 02:14
Hi @4vadim4 ,

Azurite can be reached to upload/download/delete blob with REST request. Do you mean you cannot reach Azurite with a request? Can you share detailed error you met? A little repro step would be helpful for us to investigate. 

Besides, a new issue for only what you have met would be clear for us to answer your questions.

Thanks
Emma

**Comment by EmmaZhu** [comment] 2024-01-23 02:14
Hi @smargoli2 ,  I'll look into your issue. Can you open a new issue to track it?

**Comment by EmmaZhu** [comment] 2024-01-23 03:16
Hi @smargoli2 ,  Your issue is because with the host IP address '127.0.0.1', it will only accept request from the specific container.

It works well with following command:
`docker run -p 10002:10002 mcr.microsoft.com/azure-storage/azurite azurite-table --tableHost 0.0.0.0 --tablePort 10002`

**Comment by smargoli2** [comment] 2024-01-23 10:51
Okay thanks.

**Comment by EmmaZhu** [comment] 2024-01-23 13:08
Hi @smargoli2 , can you open a new issue to track it? Could you share error you got from Azure Storage Explorer  and how you connect to Azurite from Azure Storage Explorer?

**Comment by smargoli2** [comment] 2024-01-23 17:29
Yes, thanks
https://github.com/Azure/Azurite/issues/2347
