### ISSUE TITLE
list prefix does not work with unicode characters

### ISSUE THREAD

**Issue by kahing** [Azure/Azurite#221] opened 2019-05-21 22:51 UTC
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the Azurite was used?

https://github.com/Azure/Azurite/commit/6e64127f22f0208701f0ba7cca82149fa9dbd648

### What problem was encountered?

sending list with unicode prefix (url encoded) results in 403 when using SharedKey

### Steps to reproduce the issue?

using azure sdk to send a list with `ListBlobsSegment` and unicode `Prefix`. prefix is encoded in query param like: `%2Fl%E2%94%9C%C3%A2%E2%94%AC%E2%95%A2`
works in real azure storage, fails with 403 in azurite

### Have you found a mitigation/solution?

no

**Comment by XiaoningLiu** [comment] 2019-05-30 09:52
@kahing I cannot reproduce this with Azure Storage JS SDK against Azurite V3. Please share your re-produce code if possible. Here is my sample code with JS SDK 10.3.0.

```javascript
const blobURLs = [];
    for (let i = 0; i < 3; i++) {
      const blobURL = BlobURL.fromContainerURL(
        containerURL,
        getUniqueName(`/l├â┬╢/${i}`)
      );
      const blockBlobURL = BlockBlobURL.fromBlobURL(blobURL);
      await blockBlobURL.upload(Aborter.none, "", 0);
      blobURLs.push(blobURL);
    }

    // const result = await containerURL.listBlobFlatSegment(Aborter.none, undefined, {prefix: "/l├â┬╢"});
    const result = await containerURL.listBlobFlatSegment(
      Aborter.none,
      undefined,
      { prefix: "%2Fl%E2%94%9C%C3%A2%E2%94%AC%E2%95%A2" }
    );
```

**Comment by XiaoningLiu** [comment] 2019-11-12 08:33
Will close this issue. Welcome to reopen when the issue can be reproduced.

**Closed** 2020-01-02 07:38 UTC
Labels: NewArch, question, v3.3
