### ISSUE TITLE
Frequent 500 responses from Azurite

### ISSUE THREAD

**Issue by mjyeaney** [Azure/Azurite#288] opened 2019-11-26 20:37 UTC
### Which service(blob, file, queue, table) does this issue concern?
Queue

### Which version of the Azurite was used?
Docker image (e6649aa0ef87), 2019.11 Version 3.3.0-preview

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
N/A..running as docker image

### What problem was encountered?
During local executions from async Python server (running Quart/Flask), Queue service calls are stalling with messages similar to the following:

```
2019-11-26T20:31:04.552Z 1486809f-4d17-4a86-8250-c9eb0206539d info: QueueStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/jobs/messages RequestHeaders:{"host":"127.0.0.1:10001","accept":"application/xml","x-ms-version":"2018-03-28","x-ms-date":"Tue, 26 Nov 2019 20:30:21 GMT","x-ms-client-request-id":"91ac80f0-108b-11ea-940e-9cb6d0225524","user-agent":"azsdk-python-storage-queue/12.0.0 Python/3.6.8 (Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic)","authorization":"SharedKey devstoreaccount1:a0MzuFLOAJdijnntUljPOWd1gx85GbVLtU+mV+Gc1L0=","accept-encoding":"gzip, deflate"} ClientIP=172.19.0.1 Protocol=http HTTPVersion=1.1
2019-11-26T20:31:04.552Z 1486809f-4d17-4a86-8250-c9eb0206539d info: QueueStorageContextMiddleware: Account=devstoreaccount1 Queue=jobs Message=messages MessageId=undefined
2019-11-26T20:31:04.553Z 1486809f-4d17-4a86-8250-c9eb0206539d verbose: DispatchMiddleware: Dispatching request...
2019-11-26T20:31:04.553Z 1486809f-4d17-4a86-8250-c9eb0206539d info: DispatchMiddleware: Operation=Messages_Dequeue
2019-11-26T20:31:04.553Z 1486809f-4d17-4a86-8250-c9eb0206539d verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-11-26T20:31:04.553Z 1486809f-4d17-4a86-8250-c9eb0206539d info: QueueSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-11-26T20:31:04.554Z 1486809f-4d17-4a86-8250-c9eb0206539d info: QueueSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:91ac80f0-108b-11ea-940e-9cb6d0225524\nx-ms-date:Tue, 26 Nov 2019 20:30:21 GMT\nx-ms-version:2018-03-28\n/devstoreaccount1/devstoreaccount1/jobs/messages"
2019-11-26T20:31:04.554Z 1486809f-4d17-4a86-8250-c9eb0206539d info: QueueSharedKeyAuthenticator:validate() Calculated authentication header based on key1: devstoreaccount1:a0MzuFLOAJdijnntUljPOWd1gx85GbVLtU+mV+Gc1L0=
2019-11-26T20:31:04.554Z 1486809f-4d17-4a86-8250-c9eb0206539d info: QueueSharedKeyAuthenticator:validate() Signature 1 matched.
2019-11-26T20:31:04.554Z 1486809f-4d17-4a86-8250-c9eb0206539d verbose: DeserializerMiddleware: Start deserializing...
2019-11-26T20:31:04.554Z 1486809f-4d17-4a86-8250-c9eb0206539d info: HandlerMiddleware: DeserializedParameters={"options":{"requestId":"91ac80f0-108b-11ea-940e-9cb6d0225524"},"version":"2018-03-28"}
2019-11-26T20:31:04.555Z 1486809f-4d17-4a86-8250-c9eb0206539d debug: OperationQueue.operate() Schedule incoming job f8e38d62-2dfa-4e1e-9f09-3cc1d5e3b3a1
2019-11-26T20:31:04.555Z 1486809f-4d17-4a86-8250-c9eb0206539d debug: OperationQueue:execute() Current runningConcurrency:0 maxConcurrency:100 operations.length:1
2019-11-26T20:31:04.555Z 1486809f-4d17-4a86-8250-c9eb0206539d verbose: FSExtentStore:readExtent() Creating read stream. LocationId:Default extentId:a62641c4-6f1f-4911-aae4-ddd549769613 path:/opt/azurite/__queuestorage__/a62641c4-6f1f-4911-aae4-ddd549769613 offset:165 count:55 end:219
2019-11-26T20:31:04.556Z 1486809f-4d17-4a86-8250-c9eb0206539d debug: OperationQueue.operate() Job f8e38d62-2dfa-4e1e-9f09-3cc1d5e3b3a1 completes callback, resolve.
2019-11-26T20:31:04.556Z 1486809f-4d17-4a86-8250-c9eb0206539d debug: OperationQueue:execute() Current runningConcurrency:0 maxConcurrency:100 operations.length:0
2019-11-26T20:31:04.556Z 1486809f-4d17-4a86-8250-c9eb0206539d debug: OperationQueue:execute() return. Operation.length === 0
2019-11-26T20:31:04.556Z 1486809f-4d17-4a86-8250-c9eb0206539d error: ErrorMiddleware: Received an error, fill error information to HTTP response
2019-11-26T20:31:04.556Z 1486809f-4d17-4a86-8250-c9eb0206539d error: ErrorMiddleware: ErrorName=Error ErrorMessage=ENOENT: no such file or directory, open '/opt/azurite/__queuestorage__/a62641c4-6f1f-4911-aae4-ddd549769613' ErrorStack="Error: ENOENT: no such file or directory, open '/opt/azurite/__queuestorage__/a62641c4-6f1f-4911-aae4-ddd549769613'"
2019-11-26T20:31:04.557Z 1486809f-4d17-4a86-8250-c9eb0206539d error: ErrorMiddleware: Set HTTP code: 500
2019-11-26T20:31:04.557Z 1486809f-4d17-4a86-8250-c9eb0206539d info: EndMiddleware: End response. TotalTimeInMS=5 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Queue/3.3.0-preview"}
```

This causes the Python code (running Azure storage SDK) to enter a retry loop, and ultimately stall.

### Steps to reproduce the issue?
Unknown...seems to be random.

### Have you found a mitigation/solution?
Shutting down the image for 5-10 mins, then restarting seems to help, but problem will surface again.

**Comment by mjyeaney** [comment] 2019-11-26 20:39
Note - I'm running Azurite from docker inside WSL (Ubuntu 18.04.3).

**Comment by XiaoningLiu** [comment] 2019-11-27 09:55
Hi @mjyeaney Following log shows one persisted file is missing in your local file system. Can you help check whether it exist? Also please share the full debug.log file here from start of one session until to the error happens. Thanks!

2019-11-26T20:31:04.556Z 1486809f-4d17-4a86-8250-c9eb0206539d error: ErrorMiddleware: ErrorName=Error ErrorMessage=ENOENT: no such file or directory, open '/opt/azurite/__queuestorage__/a62641c4-6f1f-4911-aae4-ddd549769613' ErrorStack="Error: ENOENT: no such file or directory, open '/opt/azurite/__queuestorage__/a62641c4-6f1f-4911-aae4-ddd549769613'"

**Comment by mjyeaney** [comment] 2019-11-27 14:20
Sure - I'll capture a log trace later today and attach. 

Also - note that I'm running this using the Docker image, so `/opt/azurute/queuestorage` isn't on my local machine, it's inside the container (which I don't have access to).

**Comment by mjyeaney** [comment] 2019-11-27 15:06
Here is the log trace from the original issue (I kept it) - note the emulator runs for a while just find, and then starts having issues near the bottom of the trace.

[debug.log](https://github.com/Azure/Azurite/files/3897407/debug.log)

**Comment by npmun** [comment] 2019-11-29 23:11
@XiaoningLiu I started noticing 500 response codes today, however, errors in my debug.log log look different. 
[debug.log](https://github.com/Azure/Azurite/files/3906519/debug.log)

`2019-11-29T23:07:36.853Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec debug: BlobSASAuthenticator:validate() Calculated signature is: JrTCBL7brwx3DZCiPzTq37iSSzTL1Z/QQk5fGcioUJs=
2019-11-29T23:07:36.853Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec info: BlobSASAuthenticator:validate() Signature based on key1 validation passed.
2019-11-29T23:07:36.853Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec info: BlobSASAuthenticator:validate() Validate start and expiry time.
2019-11-29T23:07:36.853Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec info: BlobSASAuthenticator:validate() Validate IP range.
2019-11-29T23:07:36.853Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec info: BlobSASAuthenticator:validate() Validate request protocol.
2019-11-29T23:07:36.854Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec debug: BlobSASAuthenticator:validate() Got permission requirements for operation Blob_Download - {"permission":"r"}
2019-11-29T23:07:36.854Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec info: BlobSASAuthenticator:validate() Blob service SAS validation successfully.
2019-11-29T23:07:36.854Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec verbose: DeserializerMiddleware: Start deserializing...
2019-11-29T23:07:36.854Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec info: HandlerMiddleware: DeserializedParameters={"options":{"leaseAccessConditions":{},"cpkInfo":{},"modifiedAccessConditions":{}}}
2019-11-29T23:07:36.862Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec info: BlobHandler:downloadBlockBlob() NormalizedDownloadRange=bytes=0-125497 RequiredContentLength=125498
2019-11-29T23:07:36.862Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec error: ErrorMiddleware: Received an error, fill error information to HTTP response
2019-11-29T23:07:36.862Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec error: ErrorMiddleware: ErrorName=TypeError ErrorMessage=Cannot read property 'persistencyId' of null ErrorStack="TypeError: Cannot read property 'persistencyId' of null\n    at LokiExtentMetadata.getExtentPersistencyId (C:\\Users\\pmungara\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\common\\persistence\\LokiExtentMetadataStore.js:191:20)\n    at FSExtentStore.readExtent (C:\\Users\\pmungara\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\common\\persistence\\FSExtentStore.js:201:56)\n    at bodyGetter (C:\\Users\\pmungara\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\handlers\\BlobHandler.js:510:41)\n    at BlobHandler.downloadBlockBlob (C:\\Users\\pmungara\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\handlers\\BlobHandler.js:528:26)\n    at BlobHandler.download (C:\\Users\\pmungara\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\handlers\\BlobHandler.js:53:25)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"
2019-11-29T23:07:36.862Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec error: ErrorMiddleware: Set HTTP code: 500
2019-11-29T23:07:36.862Z 8d9ec68a-de6c-4c3d-bba7-f675aa9111ec info: EndMiddleware: End response. TotalTimeInMS=10 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.3.0-preview"}`

**Comment by ManfredLange** [comment] 2019-12-01 03:52
Similar observation here. However, I'm not running it from WSL but straight as a docker container on Docker Desktop for Windows. My platform is Windows 10.

As a client I'm using C#/.NET and as a library I'm using the NuGet package `Microsoft.Azure.Storage.Queue` version 11.1.1 (https://www.nuget.org/packages/Microsoft.Azure.Storage.Queue/).

Azurite version is `Version 3.3.0-preview` according to file `ChangeLog.md` inside of the container.

**Comment by ManfredLange** [comment] 2019-12-01 04:08
> 
> 
> Sure - I'll capture a log trace later today and attach.
> 
> Also - note that I'm running this using the Docker image, so `/opt/azurute/queuestorage` isn't on my local machine, it's inside the container (which I don't have access to).

@mjyeaney You could try getting access to the docker container by executing the following command:
```docker exec -it <containerId> sh```
where <containerId> can be obtained by running this command:
```docker ps```
then looking for the entry with Image name "mcr.microsoft.com/azure-storage/azurite"
Since it is an Alpine based image, it doesn't appear to have bash installed, so sh is all you get.

Once inside the container you can ```dc``` to folders of your choice.

**Comment by mjyeaney** [comment] 2019-12-01 04:48
Thanks @ManfredLange ... always slips my mind to do that. (_facepalm_)

Anyway...not sure if this is an indication of the problem or just normal operation, but I definitely see a conflict on my system. From my error logs above, note the path that queue storage should be found at:

`EENOENT: no such file or directory, open '/opt/azurite/__queuestorage__/a62641c4-6f1f-4911-aae4-ddd549769613'`

However, on my running Docker image, the `__queuestorage` folder is **never** created at `/opt/azurite` (but note that `__blobstorage` is).  Rather, it can be found at `/data/__queuestorage__/`, which seems to match up with what the Dockerfile run command is passing in as a `-l` parameter:

`CMD ["azurite", "-l", "/data", "--blobHost", "0.0.0.0","--queueHost", "0.0.0.0"]/opt/azurite`

Is it possible there is a conflict / mismatch somewhere? After seeing this, I would expect to see `__blobstorage__` within the `/data` folder as well, but I never do.

**Comment by ManfredLange** [comment] 2019-12-01 05:02
@mjyeaney It is possible that `/data/__blobstorage` is actually on a mounted directory. If that is the case, then it may depend on the file system of your host. Since you are using WSL your host's file system is likely to be NTFS. The docker image for Azurite is based on Alpine which has poor drivers for being hosted on Windows. In my experience using Alpine-based images on Windows hosts causes issues when mounting drives. Using a nodejs based image (non-Alpine) resolved those issues.

In my case the default for queue storage appears to be `c:\azurite` on the host when I use the docker image.

I'm now experimenting with running Azurite without Docker, i.e. using Node on the host. If I see a difference, I'm fairly certain that the "culprit" is the poor drivers of the Alpine-based container image.

**Comment by mjyeaney** [comment] 2019-12-01 05:13
I'm not sharing any folders with my host machine...i.e., nothing is showing on my host c:\ drive (windows 10 as well) or on my WSL host (Ubuntu 18.04). I specifically have drive sharing turned off in Docker - no mounts in play here.

**Comment by mjyeaney** [comment] 2019-12-01 21:20
Another issue noting the path difference with Blobstorage not respecting the `-l` or `-d` parameters: 

https://github.com/Azure/Azurite/issues/286#issuecomment-559151385

**Comment by dafuchs** [comment] 2019-12-04 22:35
It seems like the issue only occurs after a message is deleted from the queue.  

Here's the sequence of events that appear to trigger it and some additional information that seems related to the cause:
1) Add message to queue
   - Creates the extent entry & extent file on disk, references the extent entry in the message entry
2) Retrieve message from queue
3) Delete message from queue
    - Removes the only reference to the extent entry
4) Queue garbage collection runs
    - No references to extent entry remaining, so it deletes the extent entry & deletes the file on disk
        Note: The file delete is deferred since the file handle created in line 1 was never closed
5) Add another message to queue
    - This re-uses the same extent file descriptor from Step 1 when writing it's extent data.  
6) Retrieve message from queue
    - Fails with the 500 error response
    - Appears to be caused by the message in Step 5 referencing it's extent that was written to the file that was marked for deletion.  While the write in step 5 appears to succeed because of the pre-existing file handle, this step attempts to create a new read handle on the file that was marked for deletion and fails.  

The file handle related portion of the code can be found in FSExtentStore::appendExtent and FSExtentStore::deleteExtents.  I'm pretty confident that is the cause of the issue; however, I haven't had time to actually come up with a code change that provides a solution.  At first glance, it seems like getting rid of the open file handles would probably go a long way to resolving it; however, that may not be the ideal solution as I assume there are reasons they were left open and cached.

**Comment by XiaoningLiu** [comment] 2019-12-10 03:33
Thanks @dafuchs I believe your investigation is pretty close to the truth. Will have a fix!

**Closed** 2019-12-26 09:26 UTC
Labels: NewArch, bug, ga, investigation, queue-storage
