### ISSUE TITLE
Escaping single quotes

### ISSUE THREAD

**Issue by davidandradeduarte** [Azure/Azurite#2009] opened 2023-06-19 15:23 UTC
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.24.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
Azurite doesn't escape single quotes properly

### Steps to reproduce the issue?
Create a table, add an entity with single quotes on either PK or RK. See the saved result.
https://github.com/davidandradeduarte/azurite-escape-odata-bug here's a repro.

**Comment by blueww** [comment] 2023-06-20 09:32
@davidandradeduarte 

We recently has a fix for Table query in Azurite, this issue might already fixed in latest code. 
Would you please try the latest code and see if the issue is fixed? You can run Azurite with latest code by following up this guild: https://github.com/Azure/Azurite#github

If the issue still can repro on latest code, would you please give Azurite debug log from latest Azurite code for further investigation?

**Comment by blueww** [comment] 2023-06-20 10:46
@davidandradeduarte 

I can repro the issue with latest Azurite code (not released).
Following is my debug log, you can see with query include single quote in the PK and RK, the "Raw response string " include an entity with single quote in the PK and RK.

Would you please check:
1. You really run Azurite from the latest Azurite code (not latest released Azurite)
2. if so, please send the debug log to create the entity with single quote in the PK and RK, then query it. Then I can compare the log with mine.

```
2023-06-20T10:38:06.332Z 73285a2e-ff28-42d5-ad20-38151178917c info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/sparkconnectortests1?$filter=PartitionKey%20eq%20%27single%27%27quota%27%20and%20RowKey%20eq%20%27single%27%27quot%27&$top=20&$select=RowKey%2Cfoo%2Cfoo2%2Cuserid%2CPartitionKey%2CTimestamp RequestHeaders:{"accept-charset":"UTF-8","maxdataserviceversion":"3.0;NetFx","accept":"application/json; odata=minimalmetadata","dataserviceversion":"3.0;","x-ms-client-request-id":"a74f3b2b-78e2-41bd-8e2c-111364338389","user-agent":"Azure-Cosmos-Table/1.0.8 (.NET CLR 4.0.30319.42000; Win32NT 10.0.19045.0)","x-ms-version":"2017-07-29","x-ms-date":"Tue, 20 Jun 2023 10:38:06 GMT","authorization":"SharedKey devstoreaccount1:D7K5ud4f7eLhfmKpuxmv5KTSNYg3xSw/3FzM+dh/l/Q=","host":"127.0.0.1:10002"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-06-20T10:38:06.333Z 73285a2e-ff28-42d5-ad20-38151178917c debug: tableStorageContextMiddleware: Dispatch pattern string: /sparkconnectortests1()
2023-06-20T10:38:06.333Z 73285a2e-ff28-42d5-ad20-38151178917c info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=sparkconnectortests1
2023-06-20T10:38:06.333Z 73285a2e-ff28-42d5-ad20-38151178917c verbose: DispatchMiddleware: Dispatching request...
2023-06-20T10:38:06.333Z 73285a2e-ff28-42d5-ad20-38151178917c info: DispatchMiddleware: Operation=Table_QueryEntities
2023-06-20T10:38:06.334Z 73285a2e-ff28-42d5-ad20-38151178917c verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2023-06-20T10:38:06.334Z 73285a2e-ff28-42d5-ad20-38151178917c info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2023-06-20T10:38:06.334Z 73285a2e-ff28-42d5-ad20-38151178917c info: TableSharedKeyLiteAuthenticator:validate() Request doesn't include valid authentication header. Skip SharedKeyLite authentication.
2023-06-20T10:38:06.335Z 73285a2e-ff28-42d5-ad20-38151178917c info: TableSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2023-06-20T10:38:06.335Z 73285a2e-ff28-42d5-ad20-38151178917c info: TableSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\nTue, 20 Jun 2023 10:38:06 GMT\n/devstoreaccount1/devstoreaccount1/sparkconnectortests1"
2023-06-20T10:38:06.335Z 73285a2e-ff28-42d5-ad20-38151178917c info: TableSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:D7K5ud4f7eLhfmKpuxmv5KTSNYg3xSw/3FzM+dh/l/Q=
2023-06-20T10:38:06.335Z 73285a2e-ff28-42d5-ad20-38151178917c info: TableSharedKeyAuthenticator:validate() Signature 1 matched.
2023-06-20T10:38:06.335Z 73285a2e-ff28-42d5-ad20-38151178917c verbose: DeserializerMiddleware: Start deserializing...
2023-06-20T10:38:06.336Z 73285a2e-ff28-42d5-ad20-38151178917c info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"top":20,"select":"RowKey,foo,foo2,userid,PartitionKey,Timestamp","filter":"PartitionKey eq 'single''quota' and RowKey eq 'single''quot'"},"requestId":"a74f3b2b-78e2-41bd-8e2c-111364338389","dataServiceVersion":"3.0;"},"version":"2017-07-29"}
2023-06-20T10:38:06.336Z 73285a2e-ff28-42d5-ad20-38151178917c debug: TableHandler:queryEntities() Raw response string is "{\"odata.metadata\":\"http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables/@Element\",\"value\":[]}"
2023-06-20T10:38:06.336Z 73285a2e-ff28-42d5-ad20-38151178917c verbose: SerializerMiddleware: Start serializing...
2023-06-20T10:38:06.336Z 73285a2e-ff28-42d5-ad20-38151178917c info: Serializer: Start returning stream body.
2023-06-20T10:38:06.338Z 73285a2e-ff28-42d5-ad20-38151178917c info: EndMiddleware: End response. TotalTimeInMS=6 StatusCode=200 StatusMessage=OK Headers={"server":"Azurite-Table/3.24.0","content-type":"application/json;odata=minimalmetadata","x-ms-client-request-id":"a74f3b2b-78e2-41bd-8e2c-111364338389","x-ms-request-id":"73285a2e-ff28-42d5-ad20-38151178917c","x-ms-version":"2023-01-03","date":"Tue, 20 Jun 2023 10:38:06 GMT"}
2023-06-20T10:38:13.997Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/sparkconnectortests1?$filter=PartitionKey%20eq%20%27single%27%27quota%27%20and%20RowKey%20eq%20%27single%27%27quota%27&$top=20&$select=RowKey%2Cfoo%2Cfoo2%2Cuserid%2CPartitionKey%2CTimestamp RequestHeaders:{"accept-charset":"UTF-8","maxdataserviceversion":"3.0;NetFx","accept":"application/json; odata=minimalmetadata","dataserviceversion":"3.0;","x-ms-client-request-id":"70f005e5-0282-4fec-af4e-59c564e317e5","user-agent":"Azure-Cosmos-Table/1.0.8 (.NET CLR 4.0.30319.42000; Win32NT 10.0.19045.0)","x-ms-version":"2017-07-29","x-ms-date":"Tue, 20 Jun 2023 10:38:13 GMT","authorization":"SharedKey devstoreaccount1:0haHmHu9etUct9i8kt3DkdhiZNMSmottQg+wCS64IvY=","host":"127.0.0.1:10002"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-06-20T10:38:13.997Z 5f11d838-6324-4793-b56e-0ce0a365a77d debug: tableStorageContextMiddleware: Dispatch pattern string: /sparkconnectortests1()
2023-06-20T10:38:13.997Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=sparkconnectortests1
2023-06-20T10:38:13.998Z 5f11d838-6324-4793-b56e-0ce0a365a77d verbose: DispatchMiddleware: Dispatching request...
2023-06-20T10:38:13.998Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: DispatchMiddleware: Operation=Table_QueryEntities
2023-06-20T10:38:13.998Z 5f11d838-6324-4793-b56e-0ce0a365a77d verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2023-06-20T10:38:13.998Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2023-06-20T10:38:13.999Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: TableSharedKeyLiteAuthenticator:validate() Request doesn't include valid authentication header. Skip SharedKeyLite authentication.
2023-06-20T10:38:13.999Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: TableSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2023-06-20T10:38:14.000Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: TableSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\nTue, 20 Jun 2023 10:38:13 GMT\n/devstoreaccount1/devstoreaccount1/sparkconnectortests1"
2023-06-20T10:38:14.000Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: TableSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:0haHmHu9etUct9i8kt3DkdhiZNMSmottQg+wCS64IvY=
2023-06-20T10:38:14.000Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: TableSharedKeyAuthenticator:validate() Signature 1 matched.
2023-06-20T10:38:14.000Z 5f11d838-6324-4793-b56e-0ce0a365a77d verbose: DeserializerMiddleware: Start deserializing...
2023-06-20T10:38:14.000Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"top":20,"select":"RowKey,foo,foo2,userid,PartitionKey,Timestamp","filter":"PartitionKey eq 'single''quota' and RowKey eq 'single''quota'"},"requestId":"70f005e5-0282-4fec-af4e-59c564e317e5","dataServiceVersion":"3.0;"},"version":"2017-07-29"}
2023-06-20T10:38:14.001Z 5f11d838-6324-4793-b56e-0ce0a365a77d debug: TableHandler:queryEntities() Raw response string is "{\"odata.metadata\":\"http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables/@Element\",\"value\":[{\"odata.etag\":\"W/\\\"datetime'2023-06-20T10%3A36%3A10.3632400Z'\\\"\",\"PartitionKey\":\"single'quota\",\"RowKey\":\"single'quota\",\"userid\":1,\"foo\":\"TestVal`\",\"Timestamp\":\"2023-06-20T10:36:10.3632400Z\"}]}"
2023-06-20T10:38:14.001Z 5f11d838-6324-4793-b56e-0ce0a365a77d verbose: SerializerMiddleware: Start serializing...
2023-06-20T10:38:14.001Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: Serializer: Start returning stream body.
2023-06-20T10:38:14.002Z 5f11d838-6324-4793-b56e-0ce0a365a77d info: EndMiddleware: End response. TotalTimeInMS=5 StatusCode=200 StatusMessage=OK Headers={"server":"Azurite-Table/3.24.0","content-type":"application/json;odata=minimalmetadata","x-ms-client-request-id":"70f005e5-0282-4fec-af4e-59c564e317e5","x-ms-request-id":"5f11d838-6324-4793-b56e-0ce0a365a77d","x-ms-version":"2023-01-03","date":"Tue, 20 Jun 2023 10:38:13 GMT"}
```

**Comment by blueww** [comment] 2023-06-21 09:20
@davidandradeduarte 

Thanks for the update!
I can repro the issue now.

The issue is in mergeEntity API, it looks will parse PK as "pk single" from `PartitionKey='pk%20single%27%27quote%20string'`.
So the saved Entity has wrong PK and RK, so you can't query it out.

The related code should be here: https://github.com/Azure/Azurite/blob/16c75cfc49b820b8ba9fee574e9bdcab3527a269/src/table/middleware/tableStorageContext.middleware.ts#L133

We would consider how to fix it, and update you later.

Azurite welcome contribution!
It would be great if you can raise a PR to fix it!

**Comment by blueww** [comment] 2023-06-30 10:01
The fix PR is already merged.
The fix will be released in the next Azurite release.

**Closed by blueww** 2023-06-30 10:01 UTC
Labels: bug, table-query
