### ISSUE TITLE
SAS: Generation for String to Sign does not support versions newer than 2020-10-02

### ISSUE THREAD

**Issue by ralfhergert** [Azure/Azurite#1389] opened 2022-03-14 09:12 UTC
We are trying to update to the latest version of com.azure:azure-storage-blob:12.15.0 and do run into an authentication issue with Azurite. The authentication issue comes down to the part for generating the "string to sign": https://github.com/Azure/Azurite/blob/3ff272f08310f7351ef852c0c12c50b32995c316/src/blob/authentication/IBlobSASSignatureValues.ts#L173

Here all versions past 2020-10-02 are not supported. For reference here is the code com.azure:azure-storage-blob uses to generate this string: https://github.com/Azure/azure-sdk-for-java/blob/f254a1b287d041481df349ae86b362cd9891adfe/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/implementation/util/BlobSasImplUtil.java#L304

My request would be whether you could introduce a generateBlobSASSignature-method for versions past 2020-10-02?

**Comment by blueww** [comment] 2022-03-14 14:31
@ralfhergert 
The SAS difference after 2020-10-02 is on Encryption scope.
Azurite does not support encryption scope now.
We will consider a fix for it. 
Azurite welcome contribution.
It would be great if you could raise a PR for the fix.

**Comment by ctolkien** [comment] 2022-03-18 01:00
I think we might be hitting this. Sas tokens fail with a 403.

Works on 12.10 of the Azure Blob nuget package, fails on 12.11.

**Comment by cadbury-sdmjc** [comment] 2022-03-22 15:14
> I think we might be hitting this. Sas tokens fail with a 403.
> 
> Works on 12.10 of the Azure Blob nuget package, fails on 12.11.

I'm seeing something similar too.

Here's how we're generating the SAS URI
```csharp
                var blob = container.GetBlobClient(request.FileId.ToString());
                var builder = new BlobSasBuilder()
                {
                    StartsOn = DateTimeOffset.UtcNow,
                    ExpiresOn = DateTimeOffset.UtcNow + TimeSpan.FromSeconds(_config.UploadSasTokenExpirySeconds),
                    BlobContainerName = container.Name,
                    BlobName = blob.Name,
                };
                builder.SetPermissions(BlobSasPermissions.Write);
                var uri = blob.GenerateSasUri(builder);
```

**Comment by Mike-E-angelo** [comment] 2022-04-04 16:21
I recently installed Azurite as Azure Storage Emulator does not support Append Block.  I am not sure Azurite supports it either as I cannot even find out because of this issue. :P  I am not sure it's the same issue as this one, either. :P :P :P  I see that azurite is version 3.14.1, and there is a 3.16.  I do not see how to upgrade to this version, and it looks like I need NPM?  So install something to install something?  I am running Visual Studio 2022 17.2 Preview 2.1 and do not have NPM installed FWIW.  I would appreciate any pointers on how to upgrade without having to install something I do not use nor have any intentions on using.

Here is the error message I get when trying to connect to my locally installed Azurite instance:
```
Azure.RequestFailedException: 'The value for one of the HTTP headers is not in the correct format.
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Additional Information:
HeaderName: x-ms-version
HeaderValue: 2021-04-10
```

**Comment by blueww** [comment] 2022-04-07 02:16
@Mike-E-angelo 
Your issue looks is a different issue then this one.
Azurite do support append blob.
It looks your error is caused by using an old Azurite version which does not support new API version "2021-04-10", but you send request with the new API version "2021-04-10".

You might can check with Visual studio team how to upgrade Azurite in Visual studio.
Or you can run Azurite with parameter "--skipApiVersionCheck", it will skip the API version check of Azurite, so the request won't fail since API version still not supported.
However, you can also install updated Azurite 3.16.0 with npm, it support API veresion 2021-04-01.

**Comment by markheath** [comment] 2022-04-07 08:06
I don't think 3.16.0 has the fix. I'm not able to use sv=2021-04-10 against Azurite 3.16.0
Looks to me like the proposed fix #1393 has not been merged yet

**Comment by Mike-E-angelo** [comment] 2022-04-07 09:42
Thank you for the suggestion @blueww.  Note that I was investigating Azurite as a replacement to the Windows-only Azure Storage Emulator, which worked _incredibly well and exactly as expected_ for my Windows-based environment up until having to use append block functionality.

Note further that I neither develop in node.js nor do I have node/NPM installed on my machine.  I hope you can understand the hesitation and apprehension to install an installer for an installer.  My expectation is to simply download a lightweight .exe and run it to have everything installed as designed and working for me, exactly how Azure Storage Emulator works.

Additionally, even finally getting Azurite to "work" with my Visual Studio install (after encountering #1414), it turns out that it launches three full CMD processes and adds them to my taskbar as three full processes.  Maybe this could be better mitigated with friendly icons, but these are not present, and the result is less than pleasant.

Compare this with the Azure Storage Emulator which hid everything cleanly with a task tray icon and was "always-on" after launch.

To add to the grief here, it seems that when these CMD processes are closed (out of sheer horror from infringing upon desktop aesthetics), they are not relaunched on the next F5.  Now I am tasked with digging through Windows explorer to find those exes (that ultimately do not currently work anyways due to this issue) to regain Azurite operability once needed.

I realize that this may be more due to Visual Studio handling your NuGet install.  But still, please consider how you are viewed here with "replacing" Azure Storage Emulator which works _incredibly well and exactly as expected_ in a Windows development environment.

All things considered, when considering the issue here along with #1414, I found your product completely unusable as presently designed.  It feels like you are not catering to Microsoft Visual Studio developers and this is beyond frustrating to me as a Microsoft-based and rooted developer.  I do appreciate, however, your team making things more cross-platform and welcoming for other parties and technologies.  I see the value in doing this.  In doing so, though, you have seemed to have forgotten those that are already actively engaged with your technologies, which seems like a rather obvious (and painful) oversight.

I would very much like to use Azurite and will continue to monitor your progress, but until you can make things better for native Microsoft (Visual Studio) developers, I am saddled with the dubious proposition of having to use a standard Azure Storage Account for development and pay those fees accordingly.

Thank you for any and all consideration of my feedback.

**Comment by theo-albers** [comment] 2022-04-16 18:50
Probably related to https://github.com/Azure/azure-sdk-for-net/issues/28172

**Comment by blueww** [comment] 2022-04-26 15:48
The fix PR is already merged: https://github.com/Azure/Azurite/pull/1429

**Comment by blueww** [comment] 2022-04-28 09:36
The SAS authentication issue is already fixed in Azurite 3.17.0.

**Comment by theo-albers** [comment] 2022-05-09 09:10
I verified the issue in our setup using Azurite 3.17.1 and Azure.Storage.Blobs version 12.12.0 (https://www.nuget.org/packages/Azure.Storage.Blobs/12.12.0) and the emulator works fine. I no longer have to use Azure.Storage.Blobs version 12.10.0. Thanks for fixing this.

**Comment by blueww** [comment] 2022-05-09 09:13
@theo-albers 
Thanks for the confirmation!
I will close the issue.

**Closed by blueww** 2022-05-09 09:13 UTC
Labels: bug, blob-storage, alignment
