### ISSUE TITLE
[Blob] Get blob property fail with 500 feature not supported error

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/Azurite#977] opened 2021-07-30 17:13 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.11-3.14
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
14.17.2

### What problem was encountered?
When using v12.6.0 @azure/storage-blob sdk to call get blob properties, the service returns a 500 error with code feature not supported.

### Steps to reproduce the issue?
Create a container in Azurite. Upload a blob to it. Install v12.6.0 blob SDK and use it to call get blob properties.

### Have you found a mitigation/solution?
No.

### Additional context
I wonder if it is due to some unsupported headers. Here is a sample request that fails. 

url: "http://127.0.0.1:10000/devstoreaccount1/bb0/telemetry-audit.txt"

headers: '{"x-ms-version":"2019-07-07","accept":"application/xml","x-ms-encryption-algorithm":"AES256","user-agent":"Microsoft Azure Storage Explorer, 1.21.0-dev, darwin azsdk-js-storageblob/12.6.0 (NODE-VERSION v14.16.0; Darwin 20.5.0)","x-ms-client-request-id":"a408ca85-e2eb-4bb2-806d-8dc5fc11448e","x-ms-date":"Fri, 30 Jul 2021 17:05:32 GMT","authorization":"redacted","cookie":""}'

And here is a successful request from v12.4.1 blob SDK.

same url: "http://127.0.0.1:10000/devstoreaccount1/bb0/telemetry-audit.txt"

headers: '{"x-ms-version":"2019-07-07","user-agent":"Microsoft Azure Storage Explorer, 1.21.0-dev, darwin azsdk-js-storageblob/12.4.1 (NODE-VERSION v14.16.0; Darwin 20.5.0)","x-ms-client-request-id":"117d4260-6b24-4ac5-9731-871ca9997dc9","x-ms-date":"Fri, 30 Jul 2021 17:10:19 GMT","authorization":"redacted","cookie":""}

The x-ms-encryption-algorithm seems to be the delta. I am not sure why the SDK adds this header. Maybe this is an SDK bug? But anyway, if Azurite doesn't support this feature, could it ignore it to unblock users?

**Comment by blueww** [comment] 2021-08-10 09:40
@JasonYeMSFT 

It seems you have already find this is caused by "x-ms-encryption-algorithm" header is not supported by Azurite.
This is a know issue of Azurite https://github.com/Azure/Azurite/issues/676

As we already has other issue to follow this for Azurite, and Python SDK has agreed to fix it, would you like to close this issue?

**Comment by JasonYeMSFT** [comment] 2021-08-10 16:59
I am fine closing it. However, I think for Azurite, at least one improvement can be to ignore the x-ms-encryption header. Sending this header to public azure without other headers that should be sent with it doesn't cause a failure in public Azure.

**Comment by blueww** [comment] 2021-08-11 02:49
@JasonYeMSFT 
Thanks for the feedback! 
Try to start Azurite with --loose, and see if the error still repro or not. Azurite will  allow more headers with --loose.

As we discussed above, I will close this issue.

**Closed by blueww** 2021-08-11 02:49 UTC
Labels: question, blob-storage, NewArch
