### ISSUE TITLE
The value for one of the HTTP headers is not in the correct format

### ISSUE THREAD

**Issue by Hristosko** [Azure/Azurite#2430] opened 2024-07-17 09:05 UTC
### Which service(blob, file, queue, table) does this issue concern?
All.

### Which version of the Azurite was used?
3.9.0 (tested with 3.8.0 as well)

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v18.18.0

### What problem was encountered?
I am trying to migrate from azurite 3.3.0-preview to the latest version 3.9.0
We have an application and tests that are using the latest azure SDK version 12.23.0.

When using the azurite 3.9.0 I always end up getting an HTTP error: **The value for one of the HTTP headers is not in the correct format**

Here is the full error from the SDK:
```
err: {
      "type": "RestError",
      "message": "The value for one of the HTTP headers is not in the correct format.\nRequestId:3e953c07-d429-4c82-a300-db4b2dee3b54\nTime:2024-07-17T08:24:14.152Z",
      "stack":
          RestError: The value for one of the HTTP headers is not in the correct format.
          RequestId:3e953c07-d429-4c82-a300-db4b2dee3b54
          Time:2024-07-17T08:24:14.152Z
      "name": "RestError",
      "code": "InvalidHeaderValue",
      "statusCode": 400,
      "request": {
        "url": "http://127.0.0.1:10000/devstoreaccount1/sastoken-v6-bucket?restype=container",
        "headers": {
          "x-ms-version": "2024-05-04",
          "accept": "application/xml",
          "user-agent": "azsdk-js-azure-storage-blob/12.23.0 core-rest-pipeline/1.16.1 Node/20.11.1 OS/(x64-Windows_NT-10.0.19045)",
          "x-ms-client-request-id": "0fa3bdcd-dda2-418a-a6b2-c159792b3777",
          "x-ms-date": "Wed, 17 Jul 2024 08:24:14 GMT",
          "authorization": "SharedKey devstoreaccount1:BbQ+42sL/AXXIKEgdrVk0XGtz2wyn5uf4xJ+nPQP370="
        },
        "method": "GET",
        "timeout": 0,
        "disableKeepAlive": false,
        "streamResponseStatusCodes": {},
        "withCredentials": false,
        "tracingOptions": {
          "tracingContext": {
            "_contextMap": {}
          }
        },
        "requestId": "0fa3bdcd-dda2-418a-a6b2-c159792b3777",
        "allowInsecureConnection": true,
        "enableBrowserStreams": false
      },
      "response": {
        "status": 400,
        "headers": {
          "server": "Azurite-Blob/3.8.0",
          "x-ms-error-code": "InvalidHeaderValue",
          "x-ms-request-id": "3e953c07-d429-4c82-a300-db4b2dee3b54",
          "content-type": "application/xml",
          "date": "Wed, 17 Jul 2024 08:24:14 GMT",
          "connection": "keep-alive",
          "keep-alive": "timeout=5",
          "transfer-encoding": "chunked"
        },
        "request": {
          "url": "http://127.0.0.1:10000/devstoreaccount1/sastoken-v6-bucket?restype=container",
          "headers": {
            "x-ms-version": "2024-05-04",
            "accept": "application/xml",
            "user-agent": "azsdk-js-azure-storage-blob/12.23.0 core-rest-pipeline/1.16.1 Node/20.11.1 OS/(x64-Windows_NT-10.0.19045)",
            "x-ms-client-request-id": "0fa3bdcd-dda2-418a-a6b2-c159792b3777",
            "x-ms-date": "Wed, 17 Jul 2024 08:24:14 GMT",
            "authorization": "SharedKey devstoreaccount1:BbQ+42sL/AXXIKEgdrVk0XGtz2wyn5uf4xJ+nPQP370="
          },
          "method": "GET",
          "timeout": 0,
          "disableKeepAlive": false,
          "streamResponseStatusCodes": {},
          "withCredentials": false,
          "tracingOptions": {
            "tracingContext": {
              "_contextMap": {}
            }
          },
          "requestId": "0fa3bdcd-dda2-418a-a6b2-c159792b3777",
          "allowInsecureConnection": true,
          "enableBrowserStreams": false
        },
        "bodyAsText": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidHeaderValue</Code>\n  <Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:3e953c07-d429-4c82-a300-db4b2dee3b54\nTime:2024-07-17T08:24:14.152Z</Message>\n  <HeaderName>x-ms-version</HeaderName>\n  <HeaderValue>2024-05-04</HeaderValue>\n</Error>",
        "parsedBody": {
          "message": "The value for one of the HTTP headers is not in the correct format.\nRequestId:3e953c07-d429-4c82-a300-db4b2dee3b54\nTime:2024-07-17T08:24:14.152Z",
          "code": "InvalidHeaderValue",
          "HeaderName": "x-ms-version",
          "HeaderValue": "2024-05-04"
        },
        "parsedHeaders": {
          "errorCode": "InvalidHeaderValue",
          "server": "Azurite-Blob/3.8.0",
          "x-ms-request-id": "3e953c07-d429-4c82-a300-db4b2dee3b54",
          "content-type": "application/xml",
          "date": "Wed, 17 Jul 2024 08:24:14 GMT",
          "connection": "keep-alive",
          "keep-alive": "timeout=5",
          "transfer-encoding": "chunked"
        }
      },
      "details": {
        "type": "Object",
        "message": "The value for one of the HTTP headers is not in the correct format.\nRequestId:3e953c07-d429-4c82-a300-db4b2dee3b54\nTime:2024-07-17T08:24:14.152Z",
        "stack":
            
        "errorCode": "InvalidHeaderValue",
        "server": "Azurite-Blob/3.8.0",
        "x-ms-request-id": "3e953c07-d429-4c82-a300-db4b2dee3b54",
        "content-type": "application/xml",
        "date": "Wed, 17 Jul 2024 08:24:14 GMT",
        "connection": "keep-alive",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked",
        "code": "InvalidHeaderValue",
        "HeaderName": "x-ms-version",
        "HeaderValue": "2024-05-04"
      }
```

### Steps to reproduce the issue?

Attached log file
[debug.log](https://github.com/user-attachments/files/16263078/debug.log)

### Have you found a mitigation/solution?

no, I haven't

**Comment by blueww** [comment] 2024-07-17 09:17
@Hristosko 

The latest Azurite is 3.31.0. See https://github.com/Azure/Azurite/releases/tag/v3.31.0

Would you please upgrade to the latest Azurite and try again?
Would you please share the whole Azurite debug log from Azurite start to the error happen?

From the error, one guess is the new SDK API version is still not supported in old Azurite version.
(Azurite 3.9.0 support API version till 2020-02-10, and js SDK 12.23.0 should use API version 2024-05-04, which only supported on Azurite 3.30.0 and later.)
If so, you can use the latest Azurite version, or start Azurite with parameter "--skipApiVersionCheck".

**Comment by blueww** [comment] 2024-07-17 09:22
@Hristosko 

I will close this issue since it's caused by not using the latest Azurite  version, and the resolution is clear.
Feel free to contact us again if need any further assistance on Azurite.

**Closed by blueww** 2024-07-17 09:22 UTC
Labels: question
