### ISSUE TITLE
Unable to check if blob exists when connecting to local emulator - Azurite

### ISSUE THREAD

**Issue by deemaher** [Azure/Azurite#935] opened 2021-07-21 00:04 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
v3.13.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Code Extension

### What's the Node.js version?
v14.15.1

### What problem was encountered?
Unable to check if a blob exists with response

### Steps to reproduce the issue?

        public AppendBlobClient getAppendBlobClient(BlobClient blobClient) {
            AppendBlobClient appendBlobClient = blobClient.getAppendBlobClient();
    
            Response<Boolean> response = appendBlobClient
                    .existsWithResponse(Duration.ofSeconds(5), Context.NONE);
        }

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

2021-07-20T23:44:57.199Z 	 info Azurite Blob service is starting on 127.0.0.1:10000
2021-07-20T23:44:57.199Z 	 info AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-07-20T23:44:57.199Z 	 info AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-07-20T23:44:57.216Z 	 info BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2021-07-20T23:44:57.216Z 	 info BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2021-07-20T23:44:57.216Z 	 info BlobGCManager:markSweepLoop() Start next mark and sweep.
2021-07-20T23:44:57.216Z 	 info BlobGCManager:markSweep() Get all extents.
2021-07-20T23:44:57.216Z 	 info BlobGCManager:start() BlobGCManager successfully started.
2021-07-20T23:44:57.216Z 	 info BlobGCManager:markSweep() Got 0 extents.
2021-07-20T23:44:57.216Z 	 info BlobGCManager:markSweep() Get referred extents.
2021-07-20T23:44:57.216Z 	 info BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2021-07-20T23:44:57.216Z 	 info BlobGCManager:markSweepLoop() Mark and sweep finished, taken 0ms.
2021-07-20T23:44:57.216Z 	 info BlobGCManager:markSweepLoop() Sleep for 600000ms.
2021-07-20T23:44:57.217Z 	 info Azurite Blob service successfully listens on http://127.0.0.1:10000
2021-07-20T23:45:07.795Z 0ef1fa05-0eea-4cf0-ba7a-f007a8902313 info BlobStorageContextMiddleware: RequestMethod=HEAD RequestURL=http://127.0.0.1/devstoreaccount1//localenvironment-localcontainer/localservice%5Crecovery%5Clocalservice%5Clocalregion%5Cprocessing%5Clocalhost_analytics.log RequestHeaders:{"host":"127.0.0.1:10000","date":"Tue, 20 Jul 2021 23:45:07 GMT","authorization":"SharedKey devstoreaccount1:5sLu4Fnjap+GZtVkTHB6FKfUHL32veYihaMELpjqFFk=","x-ms-version":"2020-08-04","x-ms-client-request-id":"03ed0abb-fca3-40a8-97db-de699e32ce67","accept":"application/xml","user-agent":"azsdk-java-azure-storage-blob/12.12.0 (1.8.0_252; Windows 10; 10.0)","content-length":"0"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2021-07-20T23:45:07.795Z 0ef1fa05-0eea-4cf0-ba7a-f007a8902313 info BlobStorageContextMiddleware: Account=devstoreaccount1 Container= Blob=localenvironment-localcontainer/localservice/recovery/localservice/localregion/processing/localhost_analytics.log
2021-07-20T23:45:07.796Z 0ef1fa05-0eea-4cf0-ba7a-f007a8902313 verbose DispatchMiddleware: Dispatching request...
2021-07-20T23:45:07.796Z 0ef1fa05-0eea-4cf0-ba7a-f007a8902313 error DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2021-07-20T23:45:07.796Z 0ef1fa05-0eea-4cf0-ba7a-f007a8902313 error ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-07-20T23:45:07.796Z 0ef1fa05-0eea-4cf0-ba7a-f007a8902313 error ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n\tat Object.dispatchMiddleware [as default] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\generated\\middleware\\dispatch.middleware.js:41:30)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\generated\\ExpressMiddlewareFactory.js:49:42\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat blobStorageContextMiddleware (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:72:5)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:14:16\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat logger (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\morgan\\index.js:144:5)\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat expressInit (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\middleware\\init.js:40:5)\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat query (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\middleware\\query.js:45:5)\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat Function.handle (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:174:3)\n\tat Function.handle (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\application.js:174:10)\n\tat Server.app (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\express.js:39:9)\n\tat Server.emit (events.js:315:20)\n\tat parserOnIncoming (_http_server.js:874:12)\n\tat HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)"
2021-07-20T23:45:07.796Z 0ef1fa05-0eea-4cf0-ba7a-f007a8902313 error ErrorMiddleware: Set HTTP code: 400
2021-07-20T23:45:07.796Z 0ef1fa05-0eea-4cf0-ba7a-f007a8902313 error ErrorMiddleware: Set HTTP body: undefined
2021-07-20T23:45:07.796Z 0ef1fa05-0eea-4cf0-ba7a-f007a8902313 info EndMiddleware: End response. TotalTimeInMS=1 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.13.1"}
2021-07-20T23:45:07.803Z 45426c49-191d-4050-bd22-8743bc978239 info BlobStorageContextMiddleware: RequestMethod=HEAD RequestURL=http://127.0.0.1/devstoreaccount1//localenvironment-localcontainer/localservice%5Crecovery%5Clocalservice%5Clocalregion%5Cprocessed%5C2021%5C07%5C20%5C19%5Canalytics_2021-07-20T19-09-33-871.log RequestHeaders:{"host":"127.0.0.1:10000","date":"Tue, 20 Jul 2021 23:45:07 GMT","authorization":"SharedKey devstoreaccount1:5eHFcJ7cik6LuKwjR2lhzw3WicijzeszswLOkTjKsRo=","x-ms-version":"2020-08-04","x-ms-client-request-id":"31757726-ba29-4e4e-b4ec-0f0f9987013d","accept":"application/xml","user-agent":"azsdk-java-azure-storage-blob/12.12.0 (1.8.0_252; Windows 10; 10.0)","content-length":"0"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2021-07-20T23:45:07.803Z 45426c49-191d-4050-bd22-8743bc978239 info BlobStorageContextMiddleware: Account=devstoreaccount1 Container= Blob=localenvironment-localcontainer/localservice/recovery/localservice/localregion/processed/2021/07/20/19/analytics_2021-07-20T19-09-33-871.log
2021-07-20T23:45:07.803Z 45426c49-191d-4050-bd22-8743bc978239 verbose DispatchMiddleware: Dispatching request...
2021-07-20T23:45:07.803Z 45426c49-191d-4050-bd22-8743bc978239 error DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2021-07-20T23:45:07.803Z 45426c49-191d-4050-bd22-8743bc978239 error ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-07-20T23:45:07.803Z 45426c49-191d-4050-bd22-8743bc978239 error ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n\tat Object.dispatchMiddleware [as default] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\generated\\middleware\\dispatch.middleware.js:41:30)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\generated\\ExpressMiddlewareFactory.js:49:42\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat blobStorageContextMiddleware (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:72:5)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:14:16\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat logger (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\morgan\\index.js:144:5)\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat expressInit (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\middleware\\init.js:40:5)\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat query (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\middleware\\query.js:45:5)\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat Function.handle (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:174:3)\n\tat Function.handle (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\application.js:174:10)\n\tat Server.app (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\express.js:39:9)\n\tat Server.emit (events.js:315:20)\n\tat parserOnIncoming (_http_server.js:874:12)\n\tat HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)"
2021-07-20T23:45:07.803Z 45426c49-191d-4050-bd22-8743bc978239 error ErrorMiddleware: Set HTTP code: 400
2021-07-20T23:45:07.803Z 45426c49-191d-4050-bd22-8743bc978239 error ErrorMiddleware: Set HTTP body: undefined
2021-07-20T23:45:07.803Z 45426c49-191d-4050-bd22-8743bc978239 info EndMiddleware: End response. TotalTimeInMS=1 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.13.1"}
2021-07-20T23:45:07.809Z 66f4e57a-f57d-4a17-bba9-746f346bc9f1 info BlobStorageContextMiddleware: RequestMethod=HEAD RequestURL=http://127.0.0.1/devstoreaccount1//localenvironment-localcontainer/localservice%2Flocalregion%2Fprocessing%2Flocalhost_analytics.log RequestHeaders:{"host":"127.0.0.1:10000","date":"Tue, 20 Jul 2021 23:45:07 GMT","authorization":"SharedKey devstoreaccount1:yhTNvw516TUUzmps24vYlcu6BoKG9NNIdbHI+6BFvPg=","x-ms-version":"2020-08-04","x-ms-client-request-id":"42378f0f-5122-4da9-8168-4e40b4bca862","accept":"application/xml","user-agent":"azsdk-java-azure-storage-blob/12.12.0 (1.8.0_252; Windows 10; 10.0)","content-length":"0"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2021-07-20T23:45:07.809Z 66f4e57a-f57d-4a17-bba9-746f346bc9f1 info BlobStorageContextMiddleware: Account=devstoreaccount1 Container= Blob=localenvironment-localcontainer/localservice/localregion/processing/localhost_analytics.log
2021-07-20T23:45:07.809Z 66f4e57a-f57d-4a17-bba9-746f346bc9f1 verbose DispatchMiddleware: Dispatching request...
2021-07-20T23:45:07.809Z 66f4e57a-f57d-4a17-bba9-746f346bc9f1 error DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2021-07-20T23:45:07.809Z 66f4e57a-f57d-4a17-bba9-746f346bc9f1 error ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-07-20T23:45:07.809Z 66f4e57a-f57d-4a17-bba9-746f346bc9f1 error ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n\tat Object.dispatchMiddleware [as default] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\generated\\middleware\\dispatch.middleware.js:41:30)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\generated\\ExpressMiddlewareFactory.js:49:42\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat blobStorageContextMiddleware (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:72:5)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:14:16\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat logger (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\morgan\\index.js:144:5)\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat expressInit (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\middleware\\init.js:40:5)\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat query (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\middleware\\query.js:45:5)\n\tat Layer.handle [as handle_request] (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n\tat trim_prefix (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:317:13)\n\tat c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:284:7\n\tat Function.process_params (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:335:12)\n\tat next (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:275:10)\n\tat Function.handle (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\router\\index.js:174:3)\n\tat Function.handle (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\application.js:174:10)\n\tat Server.app (c:\\Users\\user\\.vscode\\extensions\\azurite.azurite-3.13.1\\node_modules\\express\\lib\\express.js:39:9)\n\tat Server.emit (events.js:315:20)\n\tat parserOnIncoming (_http_server.js:874:12)\n\tat HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)"
2021-07-20T23:45:07.809Z 66f4e57a-f57d-4a17-bba9-746f346bc9f1 error ErrorMiddleware: Set HTTP code: 400
2021-07-20T23:45:07.809Z 66f4e57a-f57d-4a17-bba9-746f346bc9f1 error ErrorMiddleware: Set HTTP body: undefined
2021-07-20T23:45:07.810Z 66f4e57a-f57d-4a17-bba9-746f346bc9f1 info EndMiddleware: End response. TotalTimeInMS=0 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.13.1"}

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment] 2021-07-21 04:11
@deemaher 

It seems the blob Uri you use has some problems:
1. it has "//" after account name. Please replace it with "/"
2. Part of the Uri (blob name) seems is encoded （"/" to "%2F"）, but part of the Uri is not encoded （still "/"）. If "%2F" is not the original blob name, please use "/" instead of "%2F".

`http://127.0.0.1/devstoreaccount1//localenvironment-localcontainer/localservice%2Flocalregion%2Fprocessing%2Flocalhost_analytics.log`

**Comment by Whivel** [comment] 2021-09-23 09:06
I have the same issue:
From Node.js
`[...] http://azurite:10000/devstoreaccount1/source/prova.mp4","method":"HEAD" [...]
{"errorCode":"FeatureNotSupported","connection":"keep-alive","date":"Thu, 23 Sep 2021 08:58:01 GMT","keep-alive":"timeout=5","server":"Azurite-Blob/3.14.2","x-ms-request-id":"12351375-1ef0-4f5c-87c5-bb33b980f982"}} [...]`

From Azurite
` - [23/Sep/2021:08:58:01 +0000] "HEAD /devstoreaccount1/source/prova.mp4 HTTP/1.1" 500 -`

**Comment by blueww** [comment] 2021-09-23 09:16
@Whivel 
Would you please open a new issue with the debug log of Azurite?
Since not see "%2F" and "//" on your Uri, this might not be same issue.

**Comment by Whivel** [comment] 2021-09-23 11:47
@blueww In my case the issue was caused by the header "x-ms-encryption-algorithm", so --loose argument fixed everything.
Sorry for the noise in the topic

**Comment by blueww** [comment] 2021-09-23 11:56
@deemaher
I will close the issue as the root cause is found, and not get your responds for a long time.
Feel free to contact us if need any further assistance in Azurite.

**Closed by blueww** 2021-09-23 11:56 UTC
Labels: question, blob-storage
