### ISSUE TITLE
Major Bug: Docker Image based azurite not connecting with Docker Image based Microsoft "MS SQL Server" Instance after version since "azurite 3.24.0"

### ISSUE THREAD

**Issue by mansoorbk** [Azure/Azurite#2346] opened 2024-01-16 15:02 UTC
### Which service(blob, file, queue, table) does this issue concern?
All
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Docker Hub: mcr.microsoft.com/azure-storage/azurite:latest
### What's the Node.js version?
MS Docker Image mcr.microsoft.com/azure-storage/azurite:latest is using Node.js 14
### What problem was encountered?
Docker Image based azurite not connecting with Docker Image based Sql Server Instance
### Steps to reproduce the issue?

Use docker-compose based setup:

- Manual creation of DATABASE after database is created
- docker exec -d sql-ubuntu-2204 /opt/mssql-tools/bin/sqlcmd -S . -U sa -P "StrongPass!123" -Q "CREATE DATABASE [azurite_blob]"

---- FILE START------
version: '3.4'

services:

  sql-ubuntu-2204:
    image: mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04
    container_name: "sql-ubuntu-2204"
    hostname: sql-ubuntu-2204
    restart: always
    environment:
     - MSSQL_PID=Evaluation
     - ACCEPT_EULA=Y
     - SA_PASSWORD=StrongPass!123
    ports:
      - "1533:1433"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: "azurite"
    hostname: azurite
    restart: always
    environment:
      - AZURITE_DB=mssql://sa:StrongPass!123@host.docker.internal:1533/azurite_blob
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
---- FILE END------
If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
Exit due to unhandled error: Unexpected token '??='
Exit due to unhandled error: Unexpected token '??='
Exit due to unhandled error: Unexpected token '??='
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No. But it works with MySQL

**Comment by blueww** [comment] 2024-01-17 07:35
@mansoorbk 

Our team owns Azurite, but we are not docker expect. You issue looks a docker issue for communication between 2 docker images.

However, from the above info, I think the 1533 port in the Azurite DB connection point to the 1533 port of the Azurite docker container, but not the 1533 port of the host machine.  `- AZURITE_DB=mssql://sa:StrongPass![123@host.docker.internal](mailto:123@host.docker.internal):1533/azurite_blob` So on the 1533 port of the Azurite docker container there are no DB, so you can't connect to it.

I find some similar questions for how to connect 2 docker containers , you might can reference them.
https://stackoverflow.com/questions/45481943/connecting-two-docker-containers
https://docs.docker.com/network/network-tutorial-standalone/
https://saggu.medium.com/how-to-connect-nultiple-docker-conatiners-17f7ca72e67f

And another way might be put Sql DB and Azurite into same docker container.

**Comment by mansoorbk** [comment] 2024-01-19 12:52
@blueww .
I understand docker is not your teams expertise. But please note that azurite Docker Image is officially provided. 
But the simple problem is that
1- This is related to MSSQL Server  (Microsoft Product) support that your documentation mentions. In Documentation, example is provided for MySql Server and also tests. But not for MSSQL Server.
2- The main problem as I see is that MSSqlServer simply does not work latest "azurite" Docker Image.
3- The version that works for MSSQLServer is azurite 3.23.0. Any version above does not work with MSSQLServer.
4- Now that I have Identified the issue. How soon Can I expect the fix for MSSQLServer support.

Following is a working docker-compose example of MSSQLServer and mysql:
------YML FILE START ------
version: '3.4'

services:

  mysql:
    image: mysql:latest
    container_name: "mysql"
    hostname: mysql
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=Strong!123Pass
    ports:
      - "3306:3306"
    networks:
      - networkazurite
# Manual creation of DATABASE (IMPORTNANT!) 
#docker exec mysql mysql -u root -pStrong!123Pass -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES; create database azurite_blob;"

  mssql2202:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "mssql2202"
    hostname: mssql2202
    restart: always
    environment:
     - MSSQL_PID=Evaluation
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Strong!123Pass
    ports:
      - "1433:1433"
    networks:
      - networkazurite

# Manual creation of DATABASE (IMPORTNANT!)
#docker exec -d mssql2202 /opt/mssql-tools/bin/sqlcmd -S . -U sa -P "Strong!123Pass" -Q "CREATE DATABASE [azurite_blob]"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    container_name: "azurite"
    hostname: azurite
    restart: always
    depends_on:
      - mssql2202
      - mysql
    environment:
      - AZURITE_DB=mssql://sa:Strong!123Pass@mssql2202:1433/azurite_blob
      #- AZURITE_DB=mysql://root:Strong!123Pass@mysql:3306/azurite_blob
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - networkazurite

networks:
  networkazurite:
    name: networkazurite

**Comment by mansoorbk** [comment] 2024-01-22 13:37
@blueww Any update on findings of broken support for MS SQL Server in Azurite after version "azurite 3.23.0".
This is definitely a bug that should be put up for resolution.

**Comment by blueww** [comment] 2024-01-23 08:02
@mansoorbk 

We have mysql test for every PR in pipeline. 
https://github.com/Azure/Azurite/blob/d544d16f910e490fdd9db5565459df701895308f/azure-pipelines.yml#L146C18-L146C23

And this is Azurite blob test pass on mysql 2 weeks ago:
https://dev.azure.com/azure/Azurite/_build/results?buildId=70901&view=logs&jobId=e8602c86-c0d1-5860-9b4d-3b481418c7ab&j=e8602c86-c0d1-5860-9b4d-3b481418c7ab&t=4998437a-59db-5f46-e4f4-becf42d7217f

**Comment by blueww** [comment] 2024-01-23 08:34
@EmmaZhu 

Would you please help to follow up this issue when I am on vacation?
Thanks!

**Comment by mansoorbk** [comment] 2024-01-24 10:10
@blueww @EmmaZhu , I am not sure what your response regarding "**MySql**" has to do with my question about Microsoft "**MS SQL  Server**" ?
My problem is regarding Microsoft "MS SQL  Server" support being broken. It is clearly mentioned above.
Also, Microsoft "MS SQL  Server" is officially supported as per your documentation.
To Recap the bug. I will write my findings again.

1- This is related to MSSQL Server  (Microsoft Product) support that your documentation mentions. In Documentation, example is for Microsoft "MS SQL  Server" is not provided. It is only mentioned that it is supported.
2- I have slowly narrowed down the main problem with Microsoft "MS SQL  Server" to 3.24.0 and above "azurite" Docker Image.
3- The version that works for Microsoft "MS SQL  Server" is azurite 3.23.0.
4- Now that I have Identified the issue. How soon Can I expect the fix for Microsoft "MS SQL  Server" support?


```
# Manual creation of DATABASE (IMPORTNANT!) MS SQL Server
docker exec -d mssql2202 /opt/mssql-tools/bin/sqlcmd -S . -U sa -P "Strong!123Pass" -Q "CREATE DATABASE [azurite_blob]"

```

------YML FILE START ------

```
version: '3.4'

services:

  mssql2202:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "mssql2202"
    hostname: mssql2202
    restart: always
    environment:
     - MSSQL_PID=Evaluation
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Strong!123Pass
    ports:
      - "1433:1433"
    networks:
      - networkazurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    container_name: "azurite"
    hostname: azurite
    restart: always
    depends_on:
      - mssql2202
      - mysql
    environment:
      - AZURITE_DB=mssql://sa:Strong!123Pass@mssql2202:1433/azurite_blob
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - networkazurite

networks:
  networkazurite:
    name: networkazurite
```

**Comment by EmmaZhu** [comment] 2024-01-24 21:37
Hi @mansoorbk , I'll look into it and try to repro the issue. 
Could you share which version of OS are your using? From one of your command parameter, seems you are trying to run Azurite and mssql on ubuntu?

**Comment by EmmaZhu** [comment] 2024-01-26 02:05
Hi @mansoorbk ,

Seems I can repro this issue. I tried to start docker containers with the YML you shared, it did succeeded to start with Azurite 3.23.0 and mssql2022, but got an error like `Exit due to unhandled error: Unexpected token '??='` with Azurite 3.29.0, is it the same error as the one you got?

You shared three OS versions, are you running a Linux Container on Windows? If the error I got is the same with the one you got, I should have been able to reproduce the issue, OS version may be irrelevant. I'll look into the error I got first.

**Comment by mansoorbk** [comment] 2024-01-29 20:33
@EmmaZhu .
Yes. I am running Linux Container on Windows.

These are the details of my OS and Dev Environment.
- Windows 11 x64 Pro (10.0.22621)
- WSL2 (Ubuntu 22.04.3 LTS)
- Docker Desktop for windows (Linux containers on Windows)

**Comment by mansoorbk** [comment] 2024-01-29 20:35
@EmmaZhu  Since you can repro this bug.
Can you mark it as bug? 
It still only has label of question.

**Comment by mansoorbk** [comment] 2024-02-01 10:50
@EmmaZhu Any update ?

**Comment by EmmaZhu** [comment] 2024-02-04 08:19
Hi @mansoorbk ,

For a progress update: 
  I think it might be this change https://github.com/Azure/Azurite/commit/d98f532840c6da5c01d4e0477007c44a4bf825ac caused the failure. 
  
  I'm seeing issue when trying to upgrade to a newer version node to build a new image, also cannot validate whether my theory is correct.  I'm working on resolving current upgrade issue.

**Comment by mansoorbk** [comment] 2024-02-06 20:17
@EmmaZhu Thanks for update. Looking forward to fix.
Can you mark it as bug label? It is showing up as question label.

**Comment by mansoorbk** [comment] 2024-03-31 17:35
@EmmaZhu Any update ? This will help us alot in production

**Comment by blueww** [comment] 2024-04-01 03:14
@mansoorbk 

Emma already has a fix for this issue: https://github.com/Azure/Azurite/issues/417
We need to do more review and test on the fix. If no big issue found, we will merge this fix PR and release it in the next Azurite release which might in 2-3 weeks.

**Comment by mansoorbk** [comment] 2024-04-01 13:01
@EmmaZhu  @blueww  
Thanks for the great news. Look forward to the to being able to use mssql with azurite in prod

**Comment by EmmaZhu** [comment] 2024-09-12 05:55
Issue has been fixed. Any further investigation required, please feel free to reopen it.

**Closed by EmmaZhu** 2024-09-12 05:55 UTC
Labels: bug, question, docker
