### ISSUE TITLE
Corrupt Azurite temporary directory after changing Azure Function from .net 3.1 to .net 6

### ISSUE THREAD

**Issue by jblanchet** [Azure/Azurite#1268] opened 2022-01-07 16:58 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob Storage
### Which version of the Azurite was used?
14.17.0.0

### What problem was encountered?
After switching a C# Azure Function from .net 3.1 in process to .net 6 out of process, I was met with this error message when trying to run it from my local Visual Studio 2022:

> 
![image](https://user-images.githubusercontent.com/7320670/148578103-0405739c-62ed-43a6-a0f0-9814d12d2c74.png)

### Steps to reproduce the issue?
Something to do with switching an Azure Function from .net 3.1 to .net 6, or perhaps moving from inprocess to out of process. I have been unable to reproduce the issue after upgrading other functions in a similar way.

### Have you found a mitigation/solution?
I discovered that if I moved the entire solution to any other path, it would work. Through procmon, I discovered a temporary Azurite directory here: `C:\Users\<username>\AppData\Local\Temp\Azurite`

After deleting that directory and restarting Visual Studio, the problem was fixed.

Mentioning that that temporary directory could be corrupt in the error could have saved me hours of troubleshooting.

**Comment by blueww** [comment] 2022-01-10 03:57
@jblanchet 
Thanks for reporting this issue!
It looks like the issue is already resolved on your side.

However, from what you described, we can't find the root cause of the issue.
Azurite don't have a version of 14.17.0.0. And the error you mentioned should not be directly reported from Azurite. 
If you still want to continue investigation the issue and can repro the issue, Please share the detail repro steps, and the Azurite debug log, they might can help the investigation.

**Comment by blueww** [comment] 2022-01-11 03:37
@jblanchet 
Thanks for the reply!
If you can't give more detail repro steps, and the issue is already resolved on your side, do you mind we close this issue?

**Closed** 2022-01-11 14:50 UTC
Labels: enhancement, question, NewArch
