### ISSUE TITLE
Copy blob from an archived blob results in error

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/Azurite#1146] opened 2021-11-01 20:47 UTC
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.14.3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v14.17.3

### What problem was encountered?
Copying from an archived blob to an online blob results in error.

### Steps to reproduce the issue?
Create a block blob in azurite.
Archive it.
Copy it to an online blob using the copy blob API. https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob

We used the node sdk to perform the request, and here is the details of the request (excluding irrelevant headers) and the response:

Request:
```json
{
    "url": "http://127.0.0.1:10000/devstoreaccount1/create1/0.log",
    "method": "PUT",
    "headers": {
        "_headersMap": {
            "x-ms-version": {
                "name": "x-ms-version",
                "value": "2019-07-07"
            },
            "accept": {
                "name": "accept",
                "value": "application/xml"
            },
            "x-ms-access-tier": {
                "name": "x-ms-access-tier",
                "value": "Hot"
            },
            "x-ms-rehydrate-priority": {
                "name": "x-ms-rehydrate-priority",
                "value": "Standard"
            },
            "x-ms-copy-source": {
                "name": "x-ms-copy-source",
                "value": "http://127.0.0.1:10000/devstoreaccount1/create1/06a0ff37-6a6b-ba4c-77c0-b61d89211738.log"
            },
            "authorization": {
                "name": "Authorization",
                "value": "SharedKey (signed using the default dev key)
            }
        }
    }
}
```

Response:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<Error>\n  <Code>BlobArchived</Code>\n  <Message>This operation is not permitted on an archived blob.\nRequestId:6240b810-4842-4424-af89-0b38c3b2741d\nTime:2021-11-01T20:32:11.369Z</Message>\n</Error>
```

### Have you found a mitigation/solution?

No.

**Comment by blueww** [comment] 2021-11-02 03:05
@JasonYeMSFT 

Would you please attach the Azurite Debug log?
So we can get the info needed for invetigation.

**Comment by blueww** [comment] 2021-11-02 07:55
@JasonYeMSFT
We might has find the root cause of the issue, and has raised a fix for it. https://github.com/Azure/Azurite/pull/1148
Would you like to share the debug log? So we can confirm if the fix is right.

**Comment by JasonYeMSFT** [comment] 2021-11-02 22:19
I edited my local Azurite script with the patch but the error still reproduces. Here is a debug log containing the copy request as the last request.
[log.txt](https://github.com/Azure/Azurite/files/7464302/log.txt)

**Comment by blueww** [comment] 2021-11-03 03:20
@JasonYeMSFT

Not sure how you change the script, but the fix is in Azurite code.

From the debug log, we see the related request is "Blob_StartCopyFromURL", so the current fix should can resolve this issue.

**Closed** 2021-11-03 08:37 UTC
Labels: bug, blob-storage

**Comment by JasonYeMSFT** [comment] 2021-11-03 16:54
I go to node_modules and added the patched there. I was incorrectly using a globally installed azurite so the patch didn't work. Thanks for the fix.
