### ISSUE TITLE
Azurite Durable Functions Connection Refused

### ISSUE THREAD

**Issue by chrisrymer** [Azure/Azurite#268] opened 2019-10-28 14:57 UTC
### Which service(blob, file, queue, table) does this issue concern?
Queue
### Which version of the Azurite was used?
3.x.x
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS Code Extension
### What's the Node.js version?
v8.11.2
### What problem was encountered?
I have tried in vain over the last couple of days to get various flavours of azurite working with durable functions. Whether using v2.x.x installed via npm, or v3 manually built (or installed via VS code. I seem to be running it to the following types of error.

`Executed 'Functions.DurableFunctionsHttpStart' (Failed, Id=62b2f95e-ba13-44f1-b08b-731de1acdb77)
[28/10/2019 14:47:09] System.Private.CoreLib: Exception while executing function: Functions.DurableFunctionsHttpStart. System.Private.CoreLib: Result: Failure`

`The listener for function 'Functions.Hello' was unable to start. Microsoft.WindowsAzure.Storage: Connection refused. System.Net.Http: Connection refused. System.Private.CoreLib: Connection refused.`

I finally decided to abort my attempts at local storage and try to use a connection string from my azure portal. This worked and the initial Durable Template worked as expected.

This could be a bug, or hole in the documentation, failing that it could simply be me missing something.

### Steps to reproduce the issue?
User the Durable Functions Hello starter and try to run with Azurite via VS Code on Mac with `"AzureWebJobsStorage": "UseDevelopmentStorage=true;",` in `local.settings.json`.

### Have you found a mitigation/solution?
Use a storage account in Azure portal circumvents any issues but that only proves the Durable Functions template is fine and there is a deeper issue in the setup of Azurite and Durable Functions (or Knowledge gap)

**Comment by blueww** [comment] 2019-10-31 09:19
@chrisrymer 

From your error, it seems you client failed to connect to Azurite.
Would you please share the debug log of Azurite?
And what's the failure request you try to send to Azurite?

**Comment by chrisrymer** [comment] 2019-10-31 13:47
@blueww here is the log for azurite. The main feature of the logs appears to be this

`error ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
error ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified container already exists.  ErrorHTTPStatusCode=409 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"ContainerAlreadyExists","x-ms-request-id":"c8c41b05-13cd-4302-9f28-1c295ad013c6"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:c8c41b05-13cd-4302-9f28-1c295ad013c6\nTime:2019-10-31T13:38:05.936Z</Message>\n</Error>" ErrorStack="StorageError: The specified container already exists.\n\tat Function.getContainerAlreadyExists (/Users/someuser/.vscode/extensions/azurite.azurite-3.2.0/dist/src/blob/errors/StorageErrorFactory.js:16:16)\n\tat ContainerHandler.create (/Users/someuser/.vscode/extensions/azurite.azurite-3.2.0/dist/src/blob/handlers/ContainerHandler.js:46:49)"
error ErrorMiddleware: Set HTTP code: 409
error ErrorMiddleware: Set HTTP Header: x-ms-error-code=ContainerAlreadyExists
error ErrorMiddleware: Set HTTP Header: x-ms-request-id=c8c41b05-13cd-4302-9f28-1c295ad013c6
error ErrorMiddleware: Set content type: application/xml
error ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:c8c41b05-13cd-4302-9f28-1c295ad013c6\nTime:2019-10-31T13:38:05.936Z</Message>\n</Error>"`

Full log is here
[azurite-log.txt](https://github.com/Azure/Azurite/files/3793994/azurite-log.txt)
[func-start-log.txt](https://github.com/Azure/Azurite/files/3794009/func-start-log.txt)

**Comment by blueww** [comment] 2019-11-01 09:25
@chrisrymer

From the log, it seems there are many 409 failure on:
- Container_Create:  Since The specified container already exists
- Blob_AcquireLease: Since LeaseAlreadyPresent, and the proposedLeaseId is not aligned with the current lease ID.
(And we can see all Queue requests are successful.)

Your failure might be related with these 409 failure. 
Would you please share the Azurite DB metadata file, so we can know what's the status of the container and Blob. You can find it by：
    Find __azurite_db_blob__.json from Azurite default working location. For Azurite instance started in VSC extension, file will be in Azurite existing opening folder. For Azurite started with command line, file will be in existing Azurite process working folder. If customized work space location by --location or -l parameter, file will be in the customized location.

**Comment by chrisrymer** [comment] 2019-11-01 10:36
Sure, his is the blob
[__azurite_db_blob__.txt](https://github.com/Azure/Azurite/files/3797527/__azurite_db_blob__.txt)

Also I have provided the [repo](https://github.com/chrisrymer/durable-function-azurite) just incase there is a config problem. However the repo excludes `local.settings.json` here is the content for it.

`{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true;"
  }
}`

**Comment by blueww** [comment] 2019-11-04 09:48
@chrisrymer 
Just to confirm the "azurite_db_blob.txt" you shared , is aligned with the "azurite-log.txt" you shared .

Since some of the blob in "azurite-log.txt"  are not in "azurite_db_blob.txt", and some container/blob which failure to lease with "LeaseAlreadyPresent", is not leased in the "azurite-log.txt".

**Comment by chrisrymer** [comment] 2019-11-04 10:26
They were two difference sessions. Let me clear down and give you everything again.

**Comment by chrisrymer** [comment] 2019-11-04 10:58
[__azurite_db_blob__.json.txt](https://github.com/Azure/Azurite/files/3803652/__azurite_db_blob__.json.txt)
[__azurite_db_queue__.json.txt](https://github.com/Azure/Azurite/files/3803653/__azurite_db_queue__.json.txt)
[__azurite_db_queue_extent__.json.txt](https://github.com/Azure/Azurite/files/3803654/__azurite_db_queue_extent__.json.txt)
[Azure Storage Debug.txt](https://github.com/Azure/Azurite/files/3803655/Azure.Storage.Debug.txt)
[func-start-log.txt](https://github.com/Azure/Azurite/files/3803658/func-start-log.txt)

**Comment by blueww** [comment] 2019-11-06 09:39
@chrisrymer 
The new log has much less  error that before.
These error looks are all expected:

- 4 times 409 error: Since the same container be created 5 times, and the last 4 times failed with 409 (ContainerAlreadyExists)
- 3 times 404 error: Since the blob (or container) not created. There are request to create the blob and container after the error, and the create operation and other following operations on the blob/containers are all success.

Would you please find which request fail (or have issue), caused this failure. 
You try to debug the client, and see the detail failed request.

Or could you give a detail guild on how to run the [repo](https://github.com/chrisrymer/durable-function-azurite), so we can try to see if can repro the issue on our machine.

**Comment by chrisrymer** [comment] 2019-11-06 10:59
Add a README to the repo. Also I upgraded the azure-cli to the latest version. Now the function app will just quit with a different error `Microsoft.WindowsAzure.Storage: cannotconnect.`.

**Comment by XiaoningLiu** [comment] 2019-11-07 02:28
@chrisrymer Please open a issue/ticket to the function app team as well. If the issue is because of connection refused. It's likely function app core tryies to connect with a port Azurite doesn't serve. So from Azurite debug.log, we cannot find anything special.

**Comment by blueww** [comment] 2019-11-07 10:02
@chrisrymer 
I tried to run the repo, but I don't have a mac machine currently, so I tried to run it on my windows machine. (the code logic of Azurite on windows and Mac are very similar)
But when I try to run Step #3 on my machine, I meet following error.
I might missed some step, and what's the "console" means here?

> c:\code\durable-function-azurite>func start
> 'func' is not recognized as an internal or external command, operable program or batch file.

Could this issue be repo on Windows machine?

**Comment by chrisrymer** [comment] 2019-11-07 17:16
You need the azure cli. I am not sure how this will go trying to test azurite and function app on windows. Windows has a native storage emulator doesn't it. I suppose you could verify the code works...

Here is the azure-cli link
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest

**Comment by blueww** [comment] 2019-11-11 09:40
@chrisrymer 
I am trying to set up a Mac machine to repro that. Will need some time to do it and will update you when get some result.
It will be helpful, if you can repro this issue on a windows machine.

**Comment by chrisrymer** [comment] 2019-11-12 14:21
I think the issue lies specifically with Mac

**Comment by blueww** [comment] 2019-11-14 09:24
@chrisrymer

I have setup a Mac machine, and follow your step to clone your repo, and start Azurite in VScode on the machine.

But on step #3, when try to run "func start", I meet following error:
> -bash: func: command not found

Should I install other software or packages to have the func command?

**Comment by chrisrymer** [comment] 2019-11-14 14:05
Here is the azure-cli link
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest

**Comment by blueww** [comment] 2019-11-15 07:28
@chrisrymer

"func start" command can be found now.
But when I run it, will get 1 warning and 1 error.

- warning:
>No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

-Error:
> [11/15/19 7:23:05 AM] The 'DurableFunctionsHttpStart' function is in error: The binding type(s) 'orchestrationClient' are not registered. Please ensure the type is correct and the binding extension is installed.
> [11/15/19 7:23:05 AM] The 'DurableFunctionsOrchestratorJS' function is in error: The binding type(s) 'orchestrationTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
> [11/15/19 7:23:05 AM] The 'Hello' function is in error: The binding type(s) 'activityTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.

And I see generate 0 job (in your log, it's 3 jobs). And there are no other error.
In Azurite, see 1 container and 1 blob is created, and then continually renew release on the blob, no expected failed in Azurite. 

So how can we generate the 3 jobs to report the issue?

**Comment by blueww** [comment] 2019-11-15 07:35
/Users/weiwei/Desktop/func-start-log.txt

**Comment by blueww** [comment] 2019-11-15 07:35
/Users/weiwei/Desktop/func-start-log.txt

**Comment by XiaoningLiu** [comment] 2019-11-15 08:07
@chrisrymer Please help try with latest released 3.3.0-preview to see if the issue still happens. We did some refactor about lease implementation.

**Comment by chrisrymer** [comment] 2019-11-19 17:12
Sure OK. I will report back

**Comment by blueww** [comment] 2019-11-20 02:15
@chrisrymer
Would you please look at the above warning/errors with I run "func start" on Mac?
Is there anything missing in the repro steps?
I still can't repro the issue, seems cause by the 3 jobs can't be generated.

**Comment by chrisrymer** [comment] 2019-11-21 14:31
Ah OK. There may be some more items which you need to install to implement durable functions. Let me source that document.

**Comment by chrisrymer** [comment] 2019-11-21 14:35
@blueww also here is the ticket I raised in Functions App area.
https://github.com/Azure/azure-functions-host/issues/5214

It is still in Triage though

**Comment by chrisrymer** [comment] 2019-12-03 14:03
@blueww I am going to try and test this in 'VS Code Insiders' which is the could based version. I imagine more challenges but I will report back

**Comment by blueww** [comment] 2019-12-04 10:05
@chrisrymer 
Thanks for the update!
You might noticed we link a Azure function issue to this issue: https://github.com/Azure/azure-functions-core-tools/issues/1247
Azure function still not fully support Azurite.

**Comment by mghafoori** [comment] 2020-03-17 00:12
I am having the same issue on a Ubuntu machine, using Azurite VS Code extension. Is there any solution for this issue?

**Comment by blueww** [comment] 2020-03-17 02:35
@mghafoori 
Azure function still not fully support Azurite. So we need wait for Azure function migrate to Azurite.

**Comment by JustinGrote** [comment] 2020-03-17 04:54
@XiaoningLiu 
Based on my debugging, what is happening is that when the durable functions listeners try to write their control lease blob, Azurite is responding with '409 Blob Already Exists'
"PUT /devstoreaccount1/durablefunctionshub-leases/default/durablefunctionshub-control-00 HTTP/1.1" 409 -

Durable Functions uses the Microsoft.WindowsAzure.Storage API and it has an inner exception of "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature."

So either Azurite or the storage client is not processing the PUT request correctly according to the spec.

**Comment by JustinGrote** [comment] 2020-03-17 20:35
After patching the code and basically commenting out this section, it now behaves as expected and Durable functions work with Azurite as far as I can tell (all they do is simple blob and queue operations via Microsoft.WindowsAzure.Storage). I have a standalone EXE compiled as well as a scoop installer for testing
https://gist.github.com/JustinGrote/63983c9a53b4085d4710befea17bc913.

Obviously someone isn't behaving :)

**Comment by XiaoningLiu** [comment] 2020-03-23 08:20
Hi @JustinGrote Thanks for your investigation on this. But the pointed code is by design.

Azure Storage has the same behavior and will return 409, if:
- The blob already exists
- The second create blob (put blob) request has a `if-none-match:*` header

Actually this is a scenario to about atomic "createIfNotExist" operation.

There should some other places make the difference. For example, before the put blob request mentioned, there is a delete request to existing blob, Azure Storage deletes successfully, while Azurite failed. Then comes to the put blob 409.

**Comment by gunzip** [comment] 2020-04-11 20:14
hi @JustinGrote, when you say 

> After patching the code and basically commenting out this section, it now behaves as expected and Durable functions work with Azurite as far as I can tell

do you mean the v2 version of Azurite ? I'm asking AFAIK durable functions need table storage which azurite v3 does not support.

**Comment by JustinGrote** [comment] 2020-04-11 21:02
> hi @JustinGrote, when you say 
> 
> > After patching the code and basically commenting out this section, it now behaves as expected and Durable functions work with Azurite as far as I can tell
> 
> do you mean the v2 version of Azurite ? I'm asking AFAIK durable functions need table storage which azurite v3 does not support.
> 

I use it in conjunction with cosmosdb emulator for the table support, but I gave up and just went back to storage emulator, it's just easier.

**Comment by phanvinh0526** [comment] 2020-08-15 15:21
Hi,
Any update so far on this issue?. Since I am still getting this issue on MacOS (Durable Function V2 and Azurite)

**Comment by XiaoningLiu** [comment] 2020-08-17 02:30
Azure Durable Functions requires Azure Table which is not supported by Azurite V3 yet. However, after serveral rounds of discussion and review. Azurite V3 is going to support Table. It's great if anyone likes to contribute to Azurite V3 Table. Use following queries for all opening TODO items:
- [Phase 1 Preview Features, All](https://github.com/azure/azurite/issues?q=is%3Aissue+label%3Anewarch+label%3Atable-storage+label%3Afeatureparity+milestone%3A%22Preview+-+Azurite+V3+Table%22+is%3Aopen)
- [Phase 1 Preview Features, Unassigned](https://github.com/azure/azurite/issues?q=is%3Aissue+label%3Anewarch+label%3Atable-storage+label%3Afeatureparity+milestone%3A%22Preview+-+Azurite+V3+Table%22+is%3Aopen+no%3Aassignee)
- [Phase 1 Preview Testing, All](https://github.com/azure/azurite/issues?q=is%3Aissue+label%3Anewarch+label%3Atable-storage+label%3ATDD+milestone%3A%22Preview+-+Azurite+V3+Table%22+is%3Aopen+)
- [Phase 1 Preview Testing, Unassigned](https://github.com/azure/azurite/issues?q=is%3Aissue+label%3Anewarch+label%3Atable-storage+label%3ATDD+milestone%3A%22Preview+-+Azurite+V3+Table%22+is%3Aopen+no%3Aassignee+) 

Other references:
Azurite V3 Table GitHub Branch: https://github.com/Azure/Azurite/tree/table
Azurite V3 Table GitHub Project: https://github.com/Azure/Azurite/projects/2
Azurite V3 Table Wiki (under development): https://github.com/Azure/Azurite/wiki/Azurite-V3-Table

**Comment by edwin-huber** [comment] 2021-06-16 10:07
Durable functions now supported with preview version of Table API.

**Closed by edwin-huber** 2021-06-16 10:07 UTC
Labels: NewArch, investigation, table-storage
