### ISSUE TITLE
EACCES error when trying to start azurite

### ISSUE THREAD

**Issue by christothes** [Azure/Azurite#803] opened 2021-06-02 15:45 UTC
### Which service(blob, file, queue, table) does this issue concern?
All

### Which version of the Azurite was used?
azurite@3.12.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v14.17.0

### What problem was encountered?
When running either of these two commands to start azurite, I get an error. 

Command (either one):
`azurite-table -l \users\chriss\azurite`
`azurite -s -l \users\chriss\azurite -d \users\chriss\azurite`

Error:
```
Azurite Table service is starting on 127.0.0.1:10002
Exit die to unhandled error: listen EACCES: permission denied 127.0.0.1:10002
```

### Steps to reproduce the issue?
run the command above

Note: after running the commands above, this is the contents of my azurite dir.
```
    Directory: C:\Users\chriss\azurite

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            6/2/2021 10:41 AM                __blobstorage__
-a---            6/2/2021 10:41 AM           3934 __azurite_db_blob__.json
-a---            6/2/2021 10:41 AM           1256 __azurite_db_blob_extent__.json
-a---            6/2/2021 10:39 AM           1311 __azurite_db_table__.json
```

### Have you found a mitigation/solution?
No

**Comment by christothes** [comment] 2021-06-07 13:32
It looks like it is the system process listening on the port. Any ideas why?

> Get-Process -Id (Get-NetTCPConnection -LocalPort 10002).OwningProcess

 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
      0     0.21       6.15  26,175.81       4   0 System

**Comment by blueww** [comment] 2021-06-08 02:47
@christothes 

I don't know why System occupied port 10002, should be related with your system config.

But you can try to use another port for table, see details in https://github.com/Azure/Azurite#customize-blobqueue-service-listening-port

**Comment by christothes** [comment] 2021-06-11 20:27
I restart resolved the issue.

**Comment by blueww** [comment] 2021-06-15 03:09
@christothes 

Good to know the issue is resolved!
I will close the issue.

**Closed by blueww** 2021-06-15 03:09 UTC
Labels: question, table-storage

**Comment by giftmusandiwa** [comment] 2021-10-30 06:56
**Note**: I **resolved** the same errors received when starting azurite on **vscode**.
**Steps**: "View", "Command Palette..", "Azurerite: Start"
**Fix**: Run vscode as Administrator.

**Comment by OldManMeta** [comment] 2022-09-09 15:39
@giftmusandiwa - thank for adding that information - I was trying to execute from a command prompt and without running as Administrator, the error here is shown.

@blueww perhaps some further clarification in the documentation listed on this page to state that you must be running as admin would help?

https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio

**Comment by blueww** [comment] 2022-09-13 07:03
@OldManMeta 

Azurite doesn't need administrator permission. When the user who start Azurite has enough permission to read/write Azurite generated data (path can be specified when start Azurite) on local disk , and Azurite has access to the specified network port, Azurite should not fail since no permission.

**Comment by OldManMeta** [comment] 2022-09-13 15:19
@blueww - thanks for your response. I could not get it to work without Admin permissions.

Further more, I could not get blob-storage libraries to work with it either. CORS was an issue, having created fully open CORS polices etc, still couldn't create a container etc. Unfortunately, I just ran out of time to keep messing around and so I switched to my hosted storage account and everything works.
