### ISSUE TITLE
Azurite no longer runs correctly as a background task in GitHub Actions

### ISSUE THREAD

**Issue by LarsKemmann** [Azure/Azurite#1271] opened 2022-01-09 23:43 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.15.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
NPM

### What's the Node.js version?
14.18.2

### What problem was encountered?
I've noticed that, since today, Azurite fails to start correctly in my GitHub Actions pipeline and instead dumps some unknown text/binary content to the GitHub Action log.

Action run before the issue started:
https://github.com/CareTogether/CareTogetherCMS/runs/4710008033?check_suite_focus=true#step:6:6

Action runs showing the issue:
https://github.com/CareTogether/CareTogetherCMS/runs/4755534824?check_suite_focus=true#step:6:6 (first attempt)
https://github.com/CareTogether/CareTogetherCMS/runs/4755601564?check_suite_focus=true#step:6:6 (second attempt)
https://github.com/CareTogether/CareTogetherCMS/runs/4755632933?check_suite_focus=true#step:6:6 (third attempt, reverting my .NET SDK upgrade to try to make the Action environment as identical to the previous successful run as possible)

### Steps to reproduce the issue?
See above. It seems like the following YAML is problematic now, but wasn't as of two days ago.
```yaml
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install Azurite storage emulator
      run: npm install -g azurite
    - name: Start Azurite blob endpoint
      shell: bash
      run: azurite-blob &
```

### Have you found a mitigation/solution?
No. I can't figure out what is going on that might be affecting this. (On a related note, it would be helpful if there was some guidance provided by the Azurite GitHub readme/wiki for how to use Azurite in a GitHub Action "properly", if the above is improper somehow. I got this to work based on [guidance in an issue I found in the Azurite project](https://github.com/Azure/Azurite/issues/451#issuecomment-639398801) some time back provided by @ethomson.)

**Comment by LarsKemmann** [comment] 2022-01-10 00:05
Apologies if this turns out to not be an issue with Azurite. I've opened a GitHub Community topic as well in case it's an issue with Actions:
https://github.community/t/running-a-background-process-in-action-stopped-working/222180?u=larskemmann

Or maybe I'm crazy, in which case hopefully someone in one of the two places will be kind enough to point out what I've missed. 😊

**Comment by blueww** [comment] 2022-01-10 07:40
@LarsKemmann 

Have you do any change to Azurite (like upgrade Azurite to new version) when the issue repro? or any other changes?
From your words, it looks you have upgrade .net SDK version when the issue repro, could you confirm?

If you have not changed Azurite version, it looks more like not Azurite issue.
However, if Azurite not start from a new machine, would you like to remove the files in Azurite workspace (normally specify with `-l` when start Azurite.), and see if the issue repro?

**Comment by LarsKemmann** [comment] 2022-01-10 12:22
This is happening in GitHub Actions (check out the links to the job logs I posted).

**Comment by LarsKemmann** [comment] 2022-01-10 13:21
Okay, found the issue. You're being impacted by the "Zalgo" issue with one or both of these libraries:
- https://github.com/Marak/colors.js/issues/285
- https://github.com/Marak/faker.js

**Comment by blueww** [comment] 2022-01-11 03:41
@LarsKemmann 
Thanks for the reply!
If this is not Azurite code issue and can't resolve from Azurite side, do you mind we close this issue?

**Comment by LarsKemmann** [comment] 2022-01-11 11:58
Well, the issue is resolved now in the sense that the problem has gone away (I haven't had time to figure out what resolved it), but I sure hope the Azurite team doesn't treat a supply chain attack - that causes your code to malfunction when run by end users - as someone else's problem. That would be very concerning.

**Comment by XiaoningLiu** [comment] 2022-01-13 01:48
The difficult part is the impacted package is not direct dependency of Azurite, sometimes, in-in-in-direct dependencies. Azurite cannot pin all direct or indirect dependencies versions. That's an issue for npm packages echo system and the issue brings up to everybody in case this supply chain attack. 

Azurite other release channels like Docker Image, Visual Studio Code extension, Visual Studio built-in binary won't be impacted.

**Comment by blueww** [comment] 2022-01-18 08:48
Close as the issue is resolved currently.

**Closed by blueww** 2022-01-18 08:48 UTC
Labels: question
