### ISSUE TITLE
SharedKey Authentication Check does not work

### ISSUE THREAD

**Issue by mithrandir-wen** [Azure/Azurite#136] opened 2018-12-12 05:13 UTC
Hello, I have a problem here and I will be appreciated if someone can help me. 

According to the README document, I start Azurite with the following command:
```bash
azurite -a -l /root/file
```
However, the sharedkey authentication check does not work.

I use curl to send request to the emulator. No matter I add authentication header or not, all requests succeeded.  They succeeded even when I input the wrong access key in purpose.
(BTW: The storage account and access key I used is provided by Azure Official Document which is the following
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator)
Can anyone tell me how to solve this problem?
Thanks.

**Comment by XiaoningLiu** [comment] 2018-12-12 07:17
It's by design. Azurite doesn't validate the key. It's an emulator. For which scenarios you want to emulate by  a wrong key?

**Comment by mithrandir-wen** [comment] 2018-12-12 07:56
@XiaoningLiu Thanks for your reply.
Actually I wrote some code about authenticating into Azure Storage with storage account and access key provided by the customer for company project. Now we have entered into component test step.
The Azure Storage cost too much, so we need to use emulator to test authentication code. If the authentication check does not work in emulator, then we can not know if the code has bug or not.

So I really  need to figure out some ways to solve this problem. Any ideas? Thanks.

**Comment by XiaoningLiu** [comment] 2018-12-14 04:47
It's a feature requirement, we will discuss and investigate. However, currently we are kind of lacking resources, contributions are welcome.

**Comment by seguler** [comment] 2018-12-14 05:05
Hi @mithrandir-wen - are you sure you have checked the Azure Storage pricing ? See https://azure.microsoft.com/en-us/pricing/details/storage/blobs/

It only costs 2 cents a GB per month. 100,000 read transactions from that data will only cost 4 cents a GB. I just want to make sure you understand the pricing.

**Comment by XiaoningLiu** [comment] 2019-05-13 08:39
@mithrandir-wen We released Azurite V3 which has full support for SharedKey, Account SAS, Blob SAS authentications, welcome have a try!

**Comment by XiaoningLiu** [comment] 2019-11-12 08:46
Azurite V3 already supports SharedKey, will close this issue.

**Closed** 2020-01-02 08:02 UTC
Labels: good first feature, question, v3.3
