### ISSUE TITLE
Java azure function using @BlobInput to auto bind data from Azurite Storage

### ISSUE THREAD

**Issue by raztiff** [Azure/Azurite#270] opened 2019-10-31 16:16 UTC
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
latest V3 

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm and dockerised version 

### What's the Node.js version?
10.13.0

### What problem was encountered?
Java Azure Function using `@BlobInput` does not retrieve from Azurite storage. 

### Steps to reproduce the issue?
A Azure Function Event Grid Trigger which uses `@BlobInput` annotation, to auto bind the file using `data.url` in the event recieved by the function (see snippet)

`
@BlobInput(name = "zipfile", dataType = "binary", path = "{data.url}") final byte[] content
`

Currently tried with local installation via node installation of Azurite and latest dockerised version (`docker run -p 32788:10000 mcr.microsoft.com/azure-storage/azurite`)

File exists inside the storage, and can be downloaded, even seen using Azure Storage Explorer... The function is triggered via sending an event (e.g.http://localhost:7070/runtime/webhooks/EventGrid?functionName=MyAwesomeFunction), but the data URL used for the `@BlobInput` e.g. `http://localhost:32788/devstoreaccount1/mytestcontainer1/test.zip` **never retrieves from azurite storage and remains null**. 

Is this because the URLs don't match the same pattern as when using Azure storage e.g. `https://mystoragearea.blob.core.windows.net/mycontainer/test.zip`, or something to do with the internals of the annotation implementation? 

### Have you found a mitigation/solution?
No, assistance required.

**Comment by XiaoningLiu** [comment] 2019-11-07 02:25
Hi raztiff

Sounds interesting. So can you get the blob from url `http://localhost:32788/devstoreaccount1/mytestcontainer1/test.zip` in storage explorer? If so, mostlikly the issue is not in Azurite side. I'm not sure it's because of the url format or not. Can you help open issue for `Azure Function Event Grid Trigger`? I'm not Java or Azure Function experts, they may help you more efficiency.

**Comment by raztiff** [comment] 2019-11-08 23:26
Hi @XiaoningLiu 

Thanks for getting back tome, just getting around to reply now. I will put a an example project together and post here over the course of this weekend... I think it will just get bounced soon as mention Azurite. If it goes no where I will certainly create an issue there and link back to here in case it helps others.

**Comment by XiaoningLiu** [comment] 2019-11-12 08:13
Thanks @raztiff ! Welcome open the issue here when you have further findings. Will close this issue for now.

**Closed** 2020-01-02 03:27 UTC
Labels: NewArch, question, v3.3
